// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using MyUplinkConnector.Client.Oauth.Authorize;
using MyUplinkConnector.Client.Oauth.Consent;
using MyUplinkConnector.Client.Oauth.Error;
using MyUplinkConnector.Client.Oauth.Login;
using MyUplinkConnector.Client.Oauth.Token;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MyUplinkConnector.Client.Oauth
{
    /// <summary>
    /// Builds and executes requests for operations under \oauth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class OauthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The authorize property</summary>
        public global::MyUplinkConnector.Client.Oauth.Authorize.AuthorizeRequestBuilder Authorize
        {
            get => new global::MyUplinkConnector.Client.Oauth.Authorize.AuthorizeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The consent property</summary>
        public global::MyUplinkConnector.Client.Oauth.Consent.ConsentRequestBuilder Consent
        {
            get => new global::MyUplinkConnector.Client.Oauth.Consent.ConsentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The error property</summary>
        public global::MyUplinkConnector.Client.Oauth.Error.ErrorRequestBuilder Error
        {
            get => new global::MyUplinkConnector.Client.Oauth.Error.ErrorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The login property</summary>
        public global::MyUplinkConnector.Client.Oauth.Login.LoginRequestBuilder Login
        {
            get => new global::MyUplinkConnector.Client.Oauth.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The token property</summary>
        public global::MyUplinkConnector.Client.Oauth.Token.TokenRequestBuilder Token
        {
            get => new global::MyUplinkConnector.Client.Oauth.Token.TokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MyUplinkConnector.Client.Oauth.OauthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OauthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/oauth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MyUplinkConnector.Client.Oauth.OauthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OauthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/oauth", rawUrl)
        {
        }
    }
}
