// <auto-generated/>
#pragma warning disable CS0618
using DynessConnector.Client.V1.Device.RealTime.Data;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DynessConnector.Client.V1.Device.RealTime
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\device\realTime
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RealTimeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The data property</summary>
        public global::DynessConnector.Client.V1.Device.RealTime.Data.DataRequestBuilder Data
        {
            get => new global::DynessConnector.Client.V1.Device.RealTime.Data.DataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.V1.Device.RealTime.RealTimeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RealTimeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/device/realTime", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.V1.Device.RealTime.RealTimeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RealTimeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/device/realTime", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
