// <auto-generated/>
#pragma warning disable CS0618
using DynessConnector.Client.V1.Device.History.Export;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DynessConnector.Client.V1.Device.History
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\device\history
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HistoryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The export property</summary>
        public global::DynessConnector.Client.V1.Device.History.Export.ExportRequestBuilder Export
        {
            get => new global::DynessConnector.Client.V1.Device.History.Export.ExportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.V1.Device.History.HistoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HistoryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/device/history", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.V1.Device.History.HistoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HistoryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/device/history", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
