// <auto-generated/>
#pragma warning disable CS0618
using DynessConnector.Client.V1.Battery.Setting.Detail;
using DynessConnector.Client.V1.Battery.Setting.Set;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DynessConnector.Client.V1.Battery.Setting
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\battery\setting
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SettingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The detail property</summary>
        public global::DynessConnector.Client.V1.Battery.Setting.Detail.DetailRequestBuilder Detail
        {
            get => new global::DynessConnector.Client.V1.Battery.Setting.Detail.DetailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The set property</summary>
        public global::DynessConnector.Client.V1.Battery.Setting.Set.SetRequestBuilder Set
        {
            get => new global::DynessConnector.Client.V1.Battery.Setting.Set.SetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.V1.Battery.Setting.SettingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SettingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/battery/setting", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.V1.Battery.Setting.SettingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SettingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/battery/setting", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
