// <auto-generated/>
#pragma warning disable CS0618
using DynessConnector.Client.V1.Group.AddGroup;
using DynessConnector.Client.V1.Group.AddSnByGroup;
using DynessConnector.Client.V1.Group.BatchMaxFeedInSet;
using DynessConnector.Client.V1.Group.BatchSetChargeConfig;
using DynessConnector.Client.V1.Group.BatchSetChargeDischargeConfig;
using DynessConnector.Client.V1.Group.Control;
using DynessConnector.Client.V1.Group.GetEnergyDataByGroup;
using DynessConnector.Client.V1.Group.GetGroupList;
using DynessConnector.Client.V1.Group.GetGroupSnList;
using DynessConnector.Client.V1.Group.GetLastPowerDataByGroup;
using DynessConnector.Client.V1.Group.GetLastRunningDataByGroup;
using DynessConnector.Client.V1.Group.GetSafelyList;
using DynessConnector.Client.V1.Group.GetSystemList;
using DynessConnector.Client.V1.Group.MultiGetChargeDisChargeByGroup;
using DynessConnector.Client.V1.Group.MultiGetChargeDisChargeBySn;
using DynessConnector.Client.V1.Group.MultiGetDischargeConfigByGroup;
using DynessConnector.Client.V1.Group.MultiGetDischargeConfigBySn;
using DynessConnector.Client.V1.Group.RemoveGroup;
using DynessConnector.Client.V1.Group.RemoveSnByGroup;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DynessConnector.Client.V1.Group
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\group
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GroupRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The addGroup property</summary>
        public global::DynessConnector.Client.V1.Group.AddGroup.AddGroupRequestBuilder AddGroup
        {
            get => new global::DynessConnector.Client.V1.Group.AddGroup.AddGroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The addSnByGroup property</summary>
        public global::DynessConnector.Client.V1.Group.AddSnByGroup.AddSnByGroupRequestBuilder AddSnByGroup
        {
            get => new global::DynessConnector.Client.V1.Group.AddSnByGroup.AddSnByGroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The batchMaxFeedInSet property</summary>
        public global::DynessConnector.Client.V1.Group.BatchMaxFeedInSet.BatchMaxFeedInSetRequestBuilder BatchMaxFeedInSet
        {
            get => new global::DynessConnector.Client.V1.Group.BatchMaxFeedInSet.BatchMaxFeedInSetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The batchSetChargeConfig property</summary>
        public global::DynessConnector.Client.V1.Group.BatchSetChargeConfig.BatchSetChargeConfigRequestBuilder BatchSetChargeConfig
        {
            get => new global::DynessConnector.Client.V1.Group.BatchSetChargeConfig.BatchSetChargeConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The batchSetChargeDischargeConfig property</summary>
        public global::DynessConnector.Client.V1.Group.BatchSetChargeDischargeConfig.BatchSetChargeDischargeConfigRequestBuilder BatchSetChargeDischargeConfig
        {
            get => new global::DynessConnector.Client.V1.Group.BatchSetChargeDischargeConfig.BatchSetChargeDischargeConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The control property</summary>
        public global::DynessConnector.Client.V1.Group.Control.ControlRequestBuilder Control
        {
            get => new global::DynessConnector.Client.V1.Group.Control.ControlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getEnergyDataByGroup property</summary>
        public global::DynessConnector.Client.V1.Group.GetEnergyDataByGroup.GetEnergyDataByGroupRequestBuilder GetEnergyDataByGroup
        {
            get => new global::DynessConnector.Client.V1.Group.GetEnergyDataByGroup.GetEnergyDataByGroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getGroupList property</summary>
        public global::DynessConnector.Client.V1.Group.GetGroupList.GetGroupListRequestBuilder GetGroupList
        {
            get => new global::DynessConnector.Client.V1.Group.GetGroupList.GetGroupListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getGroupSnList property</summary>
        public global::DynessConnector.Client.V1.Group.GetGroupSnList.GetGroupSnListRequestBuilder GetGroupSnList
        {
            get => new global::DynessConnector.Client.V1.Group.GetGroupSnList.GetGroupSnListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getLastPowerDataByGroup property</summary>
        public global::DynessConnector.Client.V1.Group.GetLastPowerDataByGroup.GetLastPowerDataByGroupRequestBuilder GetLastPowerDataByGroup
        {
            get => new global::DynessConnector.Client.V1.Group.GetLastPowerDataByGroup.GetLastPowerDataByGroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getLastRunningDataByGroup property</summary>
        public global::DynessConnector.Client.V1.Group.GetLastRunningDataByGroup.GetLastRunningDataByGroupRequestBuilder GetLastRunningDataByGroup
        {
            get => new global::DynessConnector.Client.V1.Group.GetLastRunningDataByGroup.GetLastRunningDataByGroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getSafelyList property</summary>
        public global::DynessConnector.Client.V1.Group.GetSafelyList.GetSafelyListRequestBuilder GetSafelyList
        {
            get => new global::DynessConnector.Client.V1.Group.GetSafelyList.GetSafelyListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getSystemList property</summary>
        public global::DynessConnector.Client.V1.Group.GetSystemList.GetSystemListRequestBuilder GetSystemList
        {
            get => new global::DynessConnector.Client.V1.Group.GetSystemList.GetSystemListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The multiGetChargeDisChargeByGroup property</summary>
        public global::DynessConnector.Client.V1.Group.MultiGetChargeDisChargeByGroup.MultiGetChargeDisChargeByGroupRequestBuilder MultiGetChargeDisChargeByGroup
        {
            get => new global::DynessConnector.Client.V1.Group.MultiGetChargeDisChargeByGroup.MultiGetChargeDisChargeByGroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The multiGetChargeDisChargeBySn property</summary>
        public global::DynessConnector.Client.V1.Group.MultiGetChargeDisChargeBySn.MultiGetChargeDisChargeBySnRequestBuilder MultiGetChargeDisChargeBySn
        {
            get => new global::DynessConnector.Client.V1.Group.MultiGetChargeDisChargeBySn.MultiGetChargeDisChargeBySnRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The multiGetDischargeConfigByGroup property</summary>
        public global::DynessConnector.Client.V1.Group.MultiGetDischargeConfigByGroup.MultiGetDischargeConfigByGroupRequestBuilder MultiGetDischargeConfigByGroup
        {
            get => new global::DynessConnector.Client.V1.Group.MultiGetDischargeConfigByGroup.MultiGetDischargeConfigByGroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The multiGetDischargeConfigBySn property</summary>
        public global::DynessConnector.Client.V1.Group.MultiGetDischargeConfigBySn.MultiGetDischargeConfigBySnRequestBuilder MultiGetDischargeConfigBySn
        {
            get => new global::DynessConnector.Client.V1.Group.MultiGetDischargeConfigBySn.MultiGetDischargeConfigBySnRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The removeGroup property</summary>
        public global::DynessConnector.Client.V1.Group.RemoveGroup.RemoveGroupRequestBuilder RemoveGroup
        {
            get => new global::DynessConnector.Client.V1.Group.RemoveGroup.RemoveGroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The removeSnByGroup property</summary>
        public global::DynessConnector.Client.V1.Group.RemoveSnByGroup.RemoveSnByGroupRequestBuilder RemoveSnByGroup
        {
            get => new global::DynessConnector.Client.V1.Group.RemoveSnByGroup.RemoveSnByGroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.V1.Group.GroupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GroupRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/group", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.V1.Group.GroupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GroupRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/group", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
