// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using MyUplinkConnector.Client.V2.Systems.Item.Categories;
using MyUplinkConnector.Client.V2.Systems.Item.Notifications;
using MyUplinkConnector.Client.V2.Systems.Item.SmartHomeMode;
using MyUplinkConnector.Client.V2.Systems.Item.Subscriptions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MyUplinkConnector.Client.V2.Systems.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\systems\{systemId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class WithSystemItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The categories property</summary>
        public global::MyUplinkConnector.Client.V2.Systems.Item.Categories.CategoriesRequestBuilder Categories
        {
            get => new global::MyUplinkConnector.Client.V2.Systems.Item.Categories.CategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notifications property</summary>
        public global::MyUplinkConnector.Client.V2.Systems.Item.Notifications.NotificationsRequestBuilder Notifications
        {
            get => new global::MyUplinkConnector.Client.V2.Systems.Item.Notifications.NotificationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The smartHomeMode property</summary>
        public global::MyUplinkConnector.Client.V2.Systems.Item.SmartHomeMode.SmartHomeModeRequestBuilder SmartHomeMode
        {
            get => new global::MyUplinkConnector.Client.V2.Systems.Item.SmartHomeMode.SmartHomeModeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subscriptions property</summary>
        public global::MyUplinkConnector.Client.V2.Systems.Item.Subscriptions.SubscriptionsRequestBuilder Subscriptions
        {
            get => new global::MyUplinkConnector.Client.V2.Systems.Item.Subscriptions.SubscriptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MyUplinkConnector.Client.V2.Systems.Item.WithSystemItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSystemItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/systems/{systemId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MyUplinkConnector.Client.V2.Systems.Item.WithSystemItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSystemItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/systems/{systemId}", rawUrl)
        {
        }
    }
}
