// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DynessConnector.Client.Models
{
    /// <summary>
    /// Please set the parameters for each setting item individually. Batch setting is not supported!!! 
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RequestIgenAdvancedSettingDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>AC coupling function enable (0: off 1: on)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AcCoupleFuncSet { get; set; }
#nullable restore
#else
        public string AcCoupleFuncSet { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Off-grid self-start (0: off 1: on)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AutoStartBackup { get; set; }
#nullable restore
#else
        public string AutoStartBackup { get; set; }
#endif
        /// <summary>Battery activation (0: off 1: on)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryActive { get; set; }
#nullable restore
#else
        public string BatteryActive { get; set; }
#endif
        /// <summary>BoxDisable0:open1:close</summary>
        public int? BoxDisable { get; set; }
        /// <summary>Cold start</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ColdStart { get; set; }
#nullable restore
#else
        public string ColdStart { get; set; }
#endif
        /// <summary>Collector SN</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CollectorSn { get; set; }
#nullable restore
#else
        public string CollectorSn { get; set; }
#endif
        /// <summary>CT application</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CtApplication { get; set; }
#nullable restore
#else
        public string CtApplication { get; set; }
#endif
        /// <summary>Device SN</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceSn { get; set; }
#nullable restore
#else
        public string DeviceSn { get; set; }
#endif
        /// <summary>DRM Enable0:close1:open</summary>
        public int? DrmEnable { get; set; }
        /// <summary>External CT/Meter selection 0: no connection, 1: external CT, 2: external Meter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExtCtMeterEnable { get; set; }
#nullable restore
#else
        public string ExtCtMeterEnable { get; set; }
#endif
        /// <summary>Grid-connected power limit - limited power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FeedLimitPower { get; set; }
#nullable restore
#else
        public string FeedLimitPower { get; set; }
#endif
        /// <summary>Grid-connected power limit - switch</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FeedLimitSwitch { get; set; }
#nullable restore
#else
        public string FeedLimitSwitch { get; set; }
#endif
        /// <summary>Grid waveform detection</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GridWaveDetect { get; set; }
#nullable restore
#else
        public string GridWaveDetect { get; set; }
#endif
        /// <summary>High impedance mode</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HighImpedenceMode { get; set; }
#nullable restore
#else
        public string HighImpedenceMode { get; set; }
#endif
        /// <summary>ISO setting - ISO protection limit - SolarCube only</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IsoLimit { get; set; }
#nullable restore
#else
        public string IsoLimit { get; set; }
#endif
        /// <summary>Maintenance mode (for PVC only) 0: off 1: on</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaintainMode { get; set; }
#nullable restore
#else
        public string MaintainMode { get; set; }
#endif
        /// <summary>Meter application</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MeterApplication { get; set; }
#nullable restore
#else
        public string MeterApplication { get; set; }
#endif
        /// <summary>Backup power supply - backup power supply overload</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OffGridOverlordClear { get; set; }
#nullable restore
#else
        public string OffGridOverlordClear { get; set; }
#endif
        /// <summary>Backup power supply - switch</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OffGridSwitch { get; set; }
#nullable restore
#else
        public string OffGridSwitch { get; set; }
#endif
        /// <summary>Power level setting (100: 800W, 101: 1200W, 103: 2500W)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PowerLevelSetting { get; set; }
#nullable restore
#else
        public string PowerLevelSetting { get; set; }
#endif
        /// <summary>PV connection mode - SolarCube only</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PvConnectMode { get; set; }
#nullable restore
#else
        public string PvConnectMode { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.Models.RequestIgenAdvancedSettingDto"/> and sets the default values.
        /// </summary>
        public RequestIgenAdvancedSettingDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DynessConnector.Client.Models.RequestIgenAdvancedSettingDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DynessConnector.Client.Models.RequestIgenAdvancedSettingDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DynessConnector.Client.Models.RequestIgenAdvancedSettingDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "acCoupleFuncSet", n => { AcCoupleFuncSet = n.GetStringValue(); } },
                { "autoStartBackup", n => { AutoStartBackup = n.GetStringValue(); } },
                { "batteryActive", n => { BatteryActive = n.GetStringValue(); } },
                { "boxDisable", n => { BoxDisable = n.GetIntValue(); } },
                { "coldStart", n => { ColdStart = n.GetStringValue(); } },
                { "collectorSn", n => { CollectorSn = n.GetStringValue(); } },
                { "ctApplication", n => { CtApplication = n.GetStringValue(); } },
                { "deviceSn", n => { DeviceSn = n.GetStringValue(); } },
                { "drmEnable", n => { DrmEnable = n.GetIntValue(); } },
                { "extCtMeterEnable", n => { ExtCtMeterEnable = n.GetStringValue(); } },
                { "feedLimitPower", n => { FeedLimitPower = n.GetStringValue(); } },
                { "feedLimitSwitch", n => { FeedLimitSwitch = n.GetStringValue(); } },
                { "gridWaveDetect", n => { GridWaveDetect = n.GetStringValue(); } },
                { "highImpedenceMode", n => { HighImpedenceMode = n.GetStringValue(); } },
                { "isoLimit", n => { IsoLimit = n.GetStringValue(); } },
                { "maintainMode", n => { MaintainMode = n.GetStringValue(); } },
                { "meterApplication", n => { MeterApplication = n.GetStringValue(); } },
                { "offGridOverlordClear", n => { OffGridOverlordClear = n.GetStringValue(); } },
                { "offGridSwitch", n => { OffGridSwitch = n.GetStringValue(); } },
                { "powerLevelSetting", n => { PowerLevelSetting = n.GetStringValue(); } },
                { "pvConnectMode", n => { PvConnectMode = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("acCoupleFuncSet", AcCoupleFuncSet);
            writer.WriteStringValue("autoStartBackup", AutoStartBackup);
            writer.WriteStringValue("batteryActive", BatteryActive);
            writer.WriteIntValue("boxDisable", BoxDisable);
            writer.WriteStringValue("coldStart", ColdStart);
            writer.WriteStringValue("collectorSn", CollectorSn);
            writer.WriteStringValue("ctApplication", CtApplication);
            writer.WriteStringValue("deviceSn", DeviceSn);
            writer.WriteIntValue("drmEnable", DrmEnable);
            writer.WriteStringValue("extCtMeterEnable", ExtCtMeterEnable);
            writer.WriteStringValue("feedLimitPower", FeedLimitPower);
            writer.WriteStringValue("feedLimitSwitch", FeedLimitSwitch);
            writer.WriteStringValue("gridWaveDetect", GridWaveDetect);
            writer.WriteStringValue("highImpedenceMode", HighImpedenceMode);
            writer.WriteStringValue("isoLimit", IsoLimit);
            writer.WriteStringValue("maintainMode", MaintainMode);
            writer.WriteStringValue("meterApplication", MeterApplication);
            writer.WriteStringValue("offGridOverlordClear", OffGridOverlordClear);
            writer.WriteStringValue("offGridSwitch", OffGridSwitch);
            writer.WriteStringValue("powerLevelSetting", PowerLevelSetting);
            writer.WriteStringValue("pvConnectMode", PvConnectMode);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
