// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DynessConnector.Client.Models
{
    /// <summary>
    /// Batch Gourp scheduled charge and discharge setting parameters
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RequestGroupChargeDisChargeSetDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>battery working group</summary>
        public int? BatteryWorkGroup { get; set; }
        /// <summary>00:00(End time)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndTime { get; set; }
#nullable restore
#else
        public string EndTime { get; set; }
#endif
        /// <summary>group key list</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? GroupKeys { get; set; }
#nullable restore
#else
        public List<string> GroupKeys { get; set; }
#endif
        /// <summary>100%(power)</summary>
        public double? Power { get; set; }
        /// <summary>00:00(Start time)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartTime { get; set; }
#nullable restore
#else
        public string StartTime { get; set; }
#endif
        /// <summary>On/Off (Switch status)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>week</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Week { get; set; }
#nullable restore
#else
        public string Week { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.Models.RequestGroupChargeDisChargeSetDto"/> and sets the default values.
        /// </summary>
        public RequestGroupChargeDisChargeSetDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DynessConnector.Client.Models.RequestGroupChargeDisChargeSetDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DynessConnector.Client.Models.RequestGroupChargeDisChargeSetDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DynessConnector.Client.Models.RequestGroupChargeDisChargeSetDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "batteryWorkGroup", n => { BatteryWorkGroup = n.GetIntValue(); } },
                { "endTime", n => { EndTime = n.GetStringValue(); } },
                { "groupKeys", n => { GroupKeys = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "power", n => { Power = n.GetDoubleValue(); } },
                { "startTime", n => { StartTime = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "week", n => { Week = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("batteryWorkGroup", BatteryWorkGroup);
            writer.WriteStringValue("endTime", EndTime);
            writer.WriteCollectionOfPrimitiveValues<string>("groupKeys", GroupKeys);
            writer.WriteDoubleValue("power", Power);
            writer.WriteStringValue("startTime", StartTime);
            writer.WriteStringValue("state", State);
            writer.WriteStringValue("week", Week);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
