// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DynessConnector.Client.Models
{
    /// <summary>
    /// Please set the parameters for each setting item individually. Batch setting is not supported!!! 
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RequestIgenSafetyParamDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Collector SN</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CollectorSn { get; set; }
#nullable restore
#else
        public string CollectorSn { get; set; }
#endif
        /// <summary>cos φ (P) curve</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CosCurve { get; set; }
#nullable restore
#else
        public string CosCurve { get; set; }
#endif
        /// <summary>Device SN</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceSn { get; set; }
#nullable restore
#else
        public string DeviceSn { get; set; }
#endif
        /// <summary>Overfrequency load reduction curve</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FreqPowerCurve { get; set; }
#nullable restore
#else
        public string FreqPowerCurve { get; set; }
#endif
        /// <summary>High voltage ride through enable</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HvrtEnable { get; set; }
#nullable restore
#else
        public string HvrtEnable { get; set; }
#endif
        /// <summary>Level 1 overfrequency detection time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level1OverFreqTime { get; set; }
#nullable restore
#else
        public string Level1OverFreqTime { get; set; }
#endif
        /// <summary>Level 1 overfrequency trigger value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level1OverFreqValue { get; set; }
#nullable restore
#else
        public string Level1OverFreqValue { get; set; }
#endif
        /// <summary>Level 1 overvoltage detection time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level1OverVoltTime { get; set; }
#nullable restore
#else
        public string Level1OverVoltTime { get; set; }
#endif
        /// <summary>Level 1 overvoltage trigger value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level1OverVoltValue { get; set; }
#nullable restore
#else
        public string Level1OverVoltValue { get; set; }
#endif
        /// <summary>Level 1 underfrequency detection time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level1UnderFreqTime { get; set; }
#nullable restore
#else
        public string Level1UnderFreqTime { get; set; }
#endif
        /// <summary>Level 1 underfrequency trigger value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level1UnderFreqValue { get; set; }
#nullable restore
#else
        public string Level1UnderFreqValue { get; set; }
#endif
        /// <summary>Level 1 undervoltage detection time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level1UnderVoltTime { get; set; }
#nullable restore
#else
        public string Level1UnderVoltTime { get; set; }
#endif
        /// <summary>Level 1 undervoltage trigger value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level1UnderVoltValue { get; set; }
#nullable restore
#else
        public string Level1UnderVoltValue { get; set; }
#endif
        /// <summary>Level 2 overfrequency detection time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level2OverFreqTime { get; set; }
#nullable restore
#else
        public string Level2OverFreqTime { get; set; }
#endif
        /// <summary>Level 2 overfrequency trigger value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level2OverFreqValue { get; set; }
#nullable restore
#else
        public string Level2OverFreqValue { get; set; }
#endif
        /// <summary>Level 2 overvoltage detection time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level2OverVoltTime { get; set; }
#nullable restore
#else
        public string Level2OverVoltTime { get; set; }
#endif
        /// <summary>Level 2 overvoltage trigger value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level2OverVoltValue { get; set; }
#nullable restore
#else
        public string Level2OverVoltValue { get; set; }
#endif
        /// <summary>Level 2 underfrequency detection time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level2UnderFreqTime { get; set; }
#nullable restore
#else
        public string Level2UnderFreqTime { get; set; }
#endif
        /// <summary>Level 2 underfrequency trigger value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level2UnderFreqValue { get; set; }
#nullable restore
#else
        public string Level2UnderFreqValue { get; set; }
#endif
        /// <summary>Level 2 undervoltage detection time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level2UnderVoltTime { get; set; }
#nullable restore
#else
        public string Level2UnderVoltTime { get; set; }
#endif
        /// <summary>Level 2 undervoltage trigger value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level2UnderVoltValue { get; set; }
#nullable restore
#else
        public string Level2UnderVoltValue { get; set; }
#endif
        /// <summary>Level 3 overvoltage detection time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level3OverVoltTime { get; set; }
#nullable restore
#else
        public string Level3OverVoltTime { get; set; }
#endif
        /// <summary>Level 3 overvoltage trigger value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level3OverVoltValue { get; set; }
#nullable restore
#else
        public string Level3OverVoltValue { get; set; }
#endif
        /// <summary>Level 3 undervoltage detection time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level3UnderVoltTime { get; set; }
#nullable restore
#else
        public string Level3UnderVoltTime { get; set; }
#endif
        /// <summary>Level 3 undervoltage trigger value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level3UnderVoltValue { get; set; }
#nullable restore
#else
        public string Level3UnderVoltValue { get; set; }
#endif
        /// <summary>Low voltage ride through enable</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LvrtEnable { get; set; }
#nullable restore
#else
        public string LvrtEnable { get; set; }
#endif
        /// <summary>10min overvoltage trigger value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Min10OverVoltValue { get; set; }
#nullable restore
#else
        public string Min10OverVoltValue { get; set; }
#endif
        /// <summary>Grid-connected frequency lower limit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnGridFreqDownLimit { get; set; }
#nullable restore
#else
        public string OnGridFreqDownLimit { get; set; }
#endif
        /// <summary>Grid-connected frequency lower limit under fault conditions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnGridFreqDownLimitAfterFault { get; set; }
#nullable restore
#else
        public string OnGridFreqDownLimitAfterFault { get; set; }
#endif
        /// <summary>Grid-connected frequency upper limit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnGridFreqUpLimit { get; set; }
#nullable restore
#else
        public string OnGridFreqUpLimit { get; set; }
#endif
        /// <summary>Grid-connected frequency upper limit under fault conditions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnGridFreqUpLimitAfterFault { get; set; }
#nullable restore
#else
        public string OnGridFreqUpLimitAfterFault { get; set; }
#endif
        /// <summary>Grid-connected power curve slope</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnGridPowerSlope { get; set; }
#nullable restore
#else
        public string OnGridPowerSlope { get; set; }
#endif
        /// <summary>Grid-connected power curve slope under grid overvoltage fault conditions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnGridPowerSlopeAfterOverVoltFault { get; set; }
#nullable restore
#else
        public string OnGridPowerSlopeAfterOverVoltFault { get; set; }
#endif
        /// <summary>Grid-connected power curve switch</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnGridPowerSlopeEnable { get; set; }
#nullable restore
#else
        public string OnGridPowerSlopeEnable { get; set; }
#endif
        /// <summary>Grid-connected power curve switch under fault conditions (0: On 1: Off)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnGridPowerSlopeEnableAfterFault { get; set; }
#nullable restore
#else
        public string OnGridPowerSlopeEnableAfterFault { get; set; }
#endif
        /// <summary>Grid-connected power curve slope under grid overfrequency fault conditions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnGridPowerSlopeOverFreqFault { get; set; }
#nullable restore
#else
        public string OnGridPowerSlopeOverFreqFault { get; set; }
#endif
        /// <summary>Grid-connected power curve slope under grid underfrequency fault conditions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnGridPowerSlopeUnderFreqFault { get; set; }
#nullable restore
#else
        public string OnGridPowerSlopeUnderFreqFault { get; set; }
#endif
        /// <summary>Grid-connected power curve slope under grid undervoltage fault conditions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnGridPowerSlopeUnderVoltFault { get; set; }
#nullable restore
#else
        public string OnGridPowerSlopeUnderVoltFault { get; set; }
#endif
        /// <summary>Grid-connected voltage lower limit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnGridVoltDownLimit { get; set; }
#nullable restore
#else
        public string OnGridVoltDownLimit { get; set; }
#endif
        /// <summary>Grid-connected voltage lower limit under fault conditions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnGridVoltDownLimitAfterFault { get; set; }
#nullable restore
#else
        public string OnGridVoltDownLimitAfterFault { get; set; }
#endif
        /// <summary>Grid-connected voltage upper limit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnGridVoltUpLimit { get; set; }
#nullable restore
#else
        public string OnGridVoltUpLimit { get; set; }
#endif
        /// <summary>Grid-connected voltage upper limit under fault conditions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnGridVoltUpLimitAfterFault { get; set; }
#nullable restore
#else
        public string OnGridVoltUpLimitAfterFault { get; set; }
#endif
        /// <summary>Grid connection waiting time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnGridWaitTime { get; set; }
#nullable restore
#else
        public string OnGridWaitTime { get; set; }
#endif
        /// <summary>Grid connection waiting time under grid overfrequency fault conditions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnGridWaitTimeAfterGridOverFreqFault { get; set; }
#nullable restore
#else
        public string OnGridWaitTimeAfterGridOverFreqFault { get; set; }
#endif
        /// <summary>Grid connection waiting time under grid overvoltage fault conditions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnGridWaitTimeAfterGridOverVoltFault { get; set; }
#nullable restore
#else
        public string OnGridWaitTimeAfterGridOverVoltFault { get; set; }
#endif
        /// <summary>Grid connection waiting time under grid underfrequency fault conditions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnGridWaitTimeAfterGridUnderFreqFault { get; set; }
#nullable restore
#else
        public string OnGridWaitTimeAfterGridUnderFreqFault { get; set; }
#endif
        /// <summary>Grid connection waiting time under grid undervoltage fault conditions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnGridWaitTimeAfterGridUnderVoltFault { get; set; }
#nullable restore
#else
        public string OnGridWaitTimeAfterGridUnderVoltFault { get; set; }
#endif
        /// <summary>PQ curve</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PqCurve { get; set; }
#nullable restore
#else
        public string PqCurve { get; set; }
#endif
        /// <summary>PU curve</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PuCurve { get; set; }
#nullable restore
#else
        public string PuCurve { get; set; }
#endif
        /// <summary>QU curve</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? QuCurve { get; set; }
#nullable restore
#else
        public string QuCurve { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.Models.RequestIgenSafetyParamDto"/> and sets the default values.
        /// </summary>
        public RequestIgenSafetyParamDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DynessConnector.Client.Models.RequestIgenSafetyParamDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DynessConnector.Client.Models.RequestIgenSafetyParamDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DynessConnector.Client.Models.RequestIgenSafetyParamDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "collectorSn", n => { CollectorSn = n.GetStringValue(); } },
                { "cosCurve", n => { CosCurve = n.GetStringValue(); } },
                { "deviceSn", n => { DeviceSn = n.GetStringValue(); } },
                { "freqPowerCurve", n => { FreqPowerCurve = n.GetStringValue(); } },
                { "hvrtEnable", n => { HvrtEnable = n.GetStringValue(); } },
                { "level1OverFreqTime", n => { Level1OverFreqTime = n.GetStringValue(); } },
                { "level1OverFreqValue", n => { Level1OverFreqValue = n.GetStringValue(); } },
                { "level1OverVoltTime", n => { Level1OverVoltTime = n.GetStringValue(); } },
                { "level1OverVoltValue", n => { Level1OverVoltValue = n.GetStringValue(); } },
                { "level1UnderFreqTime", n => { Level1UnderFreqTime = n.GetStringValue(); } },
                { "level1UnderFreqValue", n => { Level1UnderFreqValue = n.GetStringValue(); } },
                { "level1UnderVoltTime", n => { Level1UnderVoltTime = n.GetStringValue(); } },
                { "level1UnderVoltValue", n => { Level1UnderVoltValue = n.GetStringValue(); } },
                { "level2OverFreqTime", n => { Level2OverFreqTime = n.GetStringValue(); } },
                { "level2OverFreqValue", n => { Level2OverFreqValue = n.GetStringValue(); } },
                { "level2OverVoltTime", n => { Level2OverVoltTime = n.GetStringValue(); } },
                { "level2OverVoltValue", n => { Level2OverVoltValue = n.GetStringValue(); } },
                { "level2UnderFreqTime", n => { Level2UnderFreqTime = n.GetStringValue(); } },
                { "level2UnderFreqValue", n => { Level2UnderFreqValue = n.GetStringValue(); } },
                { "level2UnderVoltTime", n => { Level2UnderVoltTime = n.GetStringValue(); } },
                { "level2UnderVoltValue", n => { Level2UnderVoltValue = n.GetStringValue(); } },
                { "level3OverVoltTime", n => { Level3OverVoltTime = n.GetStringValue(); } },
                { "level3OverVoltValue", n => { Level3OverVoltValue = n.GetStringValue(); } },
                { "level3UnderVoltTime", n => { Level3UnderVoltTime = n.GetStringValue(); } },
                { "level3UnderVoltValue", n => { Level3UnderVoltValue = n.GetStringValue(); } },
                { "lvrtEnable", n => { LvrtEnable = n.GetStringValue(); } },
                { "min10OverVoltValue", n => { Min10OverVoltValue = n.GetStringValue(); } },
                { "onGridFreqDownLimit", n => { OnGridFreqDownLimit = n.GetStringValue(); } },
                { "onGridFreqDownLimitAfterFault", n => { OnGridFreqDownLimitAfterFault = n.GetStringValue(); } },
                { "onGridFreqUpLimit", n => { OnGridFreqUpLimit = n.GetStringValue(); } },
                { "onGridFreqUpLimitAfterFault", n => { OnGridFreqUpLimitAfterFault = n.GetStringValue(); } },
                { "onGridPowerSlope", n => { OnGridPowerSlope = n.GetStringValue(); } },
                { "onGridPowerSlopeAfterOverVoltFault", n => { OnGridPowerSlopeAfterOverVoltFault = n.GetStringValue(); } },
                { "onGridPowerSlopeEnable", n => { OnGridPowerSlopeEnable = n.GetStringValue(); } },
                { "onGridPowerSlopeEnableAfterFault", n => { OnGridPowerSlopeEnableAfterFault = n.GetStringValue(); } },
                { "onGridPowerSlopeOverFreqFault", n => { OnGridPowerSlopeOverFreqFault = n.GetStringValue(); } },
                { "onGridPowerSlopeUnderFreqFault", n => { OnGridPowerSlopeUnderFreqFault = n.GetStringValue(); } },
                { "onGridPowerSlopeUnderVoltFault", n => { OnGridPowerSlopeUnderVoltFault = n.GetStringValue(); } },
                { "onGridVoltDownLimit", n => { OnGridVoltDownLimit = n.GetStringValue(); } },
                { "onGridVoltDownLimitAfterFault", n => { OnGridVoltDownLimitAfterFault = n.GetStringValue(); } },
                { "onGridVoltUpLimit", n => { OnGridVoltUpLimit = n.GetStringValue(); } },
                { "onGridVoltUpLimitAfterFault", n => { OnGridVoltUpLimitAfterFault = n.GetStringValue(); } },
                { "onGridWaitTime", n => { OnGridWaitTime = n.GetStringValue(); } },
                { "onGridWaitTimeAfterGridOverFreqFault", n => { OnGridWaitTimeAfterGridOverFreqFault = n.GetStringValue(); } },
                { "onGridWaitTimeAfterGridOverVoltFault", n => { OnGridWaitTimeAfterGridOverVoltFault = n.GetStringValue(); } },
                { "onGridWaitTimeAfterGridUnderFreqFault", n => { OnGridWaitTimeAfterGridUnderFreqFault = n.GetStringValue(); } },
                { "onGridWaitTimeAfterGridUnderVoltFault", n => { OnGridWaitTimeAfterGridUnderVoltFault = n.GetStringValue(); } },
                { "pqCurve", n => { PqCurve = n.GetStringValue(); } },
                { "puCurve", n => { PuCurve = n.GetStringValue(); } },
                { "quCurve", n => { QuCurve = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("collectorSn", CollectorSn);
            writer.WriteStringValue("cosCurve", CosCurve);
            writer.WriteStringValue("deviceSn", DeviceSn);
            writer.WriteStringValue("freqPowerCurve", FreqPowerCurve);
            writer.WriteStringValue("hvrtEnable", HvrtEnable);
            writer.WriteStringValue("level1OverFreqTime", Level1OverFreqTime);
            writer.WriteStringValue("level1OverFreqValue", Level1OverFreqValue);
            writer.WriteStringValue("level1OverVoltTime", Level1OverVoltTime);
            writer.WriteStringValue("level1OverVoltValue", Level1OverVoltValue);
            writer.WriteStringValue("level1UnderFreqTime", Level1UnderFreqTime);
            writer.WriteStringValue("level1UnderFreqValue", Level1UnderFreqValue);
            writer.WriteStringValue("level1UnderVoltTime", Level1UnderVoltTime);
            writer.WriteStringValue("level1UnderVoltValue", Level1UnderVoltValue);
            writer.WriteStringValue("level2OverFreqTime", Level2OverFreqTime);
            writer.WriteStringValue("level2OverFreqValue", Level2OverFreqValue);
            writer.WriteStringValue("level2OverVoltTime", Level2OverVoltTime);
            writer.WriteStringValue("level2OverVoltValue", Level2OverVoltValue);
            writer.WriteStringValue("level2UnderFreqTime", Level2UnderFreqTime);
            writer.WriteStringValue("level2UnderFreqValue", Level2UnderFreqValue);
            writer.WriteStringValue("level2UnderVoltTime", Level2UnderVoltTime);
            writer.WriteStringValue("level2UnderVoltValue", Level2UnderVoltValue);
            writer.WriteStringValue("level3OverVoltTime", Level3OverVoltTime);
            writer.WriteStringValue("level3OverVoltValue", Level3OverVoltValue);
            writer.WriteStringValue("level3UnderVoltTime", Level3UnderVoltTime);
            writer.WriteStringValue("level3UnderVoltValue", Level3UnderVoltValue);
            writer.WriteStringValue("lvrtEnable", LvrtEnable);
            writer.WriteStringValue("min10OverVoltValue", Min10OverVoltValue);
            writer.WriteStringValue("onGridFreqDownLimit", OnGridFreqDownLimit);
            writer.WriteStringValue("onGridFreqDownLimitAfterFault", OnGridFreqDownLimitAfterFault);
            writer.WriteStringValue("onGridFreqUpLimit", OnGridFreqUpLimit);
            writer.WriteStringValue("onGridFreqUpLimitAfterFault", OnGridFreqUpLimitAfterFault);
            writer.WriteStringValue("onGridPowerSlope", OnGridPowerSlope);
            writer.WriteStringValue("onGridPowerSlopeAfterOverVoltFault", OnGridPowerSlopeAfterOverVoltFault);
            writer.WriteStringValue("onGridPowerSlopeEnable", OnGridPowerSlopeEnable);
            writer.WriteStringValue("onGridPowerSlopeEnableAfterFault", OnGridPowerSlopeEnableAfterFault);
            writer.WriteStringValue("onGridPowerSlopeOverFreqFault", OnGridPowerSlopeOverFreqFault);
            writer.WriteStringValue("onGridPowerSlopeUnderFreqFault", OnGridPowerSlopeUnderFreqFault);
            writer.WriteStringValue("onGridPowerSlopeUnderVoltFault", OnGridPowerSlopeUnderVoltFault);
            writer.WriteStringValue("onGridVoltDownLimit", OnGridVoltDownLimit);
            writer.WriteStringValue("onGridVoltDownLimitAfterFault", OnGridVoltDownLimitAfterFault);
            writer.WriteStringValue("onGridVoltUpLimit", OnGridVoltUpLimit);
            writer.WriteStringValue("onGridVoltUpLimitAfterFault", OnGridVoltUpLimitAfterFault);
            writer.WriteStringValue("onGridWaitTime", OnGridWaitTime);
            writer.WriteStringValue("onGridWaitTimeAfterGridOverFreqFault", OnGridWaitTimeAfterGridOverFreqFault);
            writer.WriteStringValue("onGridWaitTimeAfterGridOverVoltFault", OnGridWaitTimeAfterGridOverVoltFault);
            writer.WriteStringValue("onGridWaitTimeAfterGridUnderFreqFault", OnGridWaitTimeAfterGridUnderFreqFault);
            writer.WriteStringValue("onGridWaitTimeAfterGridUnderVoltFault", OnGridWaitTimeAfterGridUnderVoltFault);
            writer.WriteStringValue("pqCurve", PqCurve);
            writer.WriteStringValue("puCurve", PuCurve);
            writer.WriteStringValue("quCurve", QuCurve);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
