// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DynessConnector.Client.Models
{
    /// <summary>
    /// list object
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResponseDynamicListDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreateTime { get; set; }
#nullable restore
#else
        public string CreateTime { get; set; }
#endif
        /// <summary>pcs power|total inverter power</summary>
        public double? InverterTotalPower { get; set; }
        /// <summary>real time current</summary>
        public double? RealTimeCurrent { get; set; }
        /// <summary>real time current</summary>
        public double? RealTimeCurrent2 { get; set; }
        /// <summary>real time power</summary>
        public double? RealTimePower { get; set; }
        /// <summary>real time power</summary>
        public double? RealTimePower2 { get; set; }
        /// <summary>实时电压</summary>
        public double? RealTimeVoltage { get; set; }
        /// <summary>battery remaining capacity</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Soc { get; set; }
#nullable restore
#else
        public string Soc { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.Models.ResponseDynamicListDto"/> and sets the default values.
        /// </summary>
        public ResponseDynamicListDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DynessConnector.Client.Models.ResponseDynamicListDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DynessConnector.Client.Models.ResponseDynamicListDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DynessConnector.Client.Models.ResponseDynamicListDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createTime", n => { CreateTime = n.GetStringValue(); } },
                { "inverterTotalPower", n => { InverterTotalPower = n.GetDoubleValue(); } },
                { "realTimeCurrent", n => { RealTimeCurrent = n.GetDoubleValue(); } },
                { "realTimeCurrent2", n => { RealTimeCurrent2 = n.GetDoubleValue(); } },
                { "realTimePower", n => { RealTimePower = n.GetDoubleValue(); } },
                { "realTimePower2", n => { RealTimePower2 = n.GetDoubleValue(); } },
                { "realTimeVoltage", n => { RealTimeVoltage = n.GetDoubleValue(); } },
                { "soc", n => { Soc = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("createTime", CreateTime);
            writer.WriteDoubleValue("inverterTotalPower", InverterTotalPower);
            writer.WriteDoubleValue("realTimeCurrent", RealTimeCurrent);
            writer.WriteDoubleValue("realTimeCurrent2", RealTimeCurrent2);
            writer.WriteDoubleValue("realTimePower", RealTimePower);
            writer.WriteDoubleValue("realTimePower2", RealTimePower2);
            writer.WriteDoubleValue("realTimeVoltage", RealTimeVoltage);
            writer.WriteStringValue("soc", Soc);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
