// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DynessConnector.Client.Models
{
    /// <summary>
    /// Real-time data of the power grid connected to the grid
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResponseOpenApiParallelRealtimeDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Battery current</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryCurrent { get; set; }
#nullable restore
#else
        public string BatteryCurrent { get; set; }
#endif
        /// <summary>Battery current - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryCurrentUnit { get; set; }
#nullable restore
#else
        public string BatteryCurrentUnit { get; set; }
#endif
        /// <summary>Battery power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryPower { get; set; }
#nullable restore
#else
        public string BatteryPower { get; set; }
#endif
        /// <summary>Battery power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryPowerUnit { get; set; }
#nullable restore
#else
        public string BatteryPowerUnit { get; set; }
#endif
        /// <summary>Battery soc</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatterySoc { get; set; }
#nullable restore
#else
        public string BatterySoc { get; set; }
#endif
        /// <summary>Input power of photovoltaic inverter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatterySocUnit { get; set; }
#nullable restore
#else
        public string BatterySocUnit { get; set; }
#endif
        /// <summary>Battery status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryStatus { get; set; }
#nullable restore
#else
        public string BatteryStatus { get; set; }
#endif
        /// <summary>Battery voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryVoltage { get; set; }
#nullable restore
#else
        public string BatteryVoltage { get; set; }
#endif
        /// <summary>Battery voltage - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryVoltageUnit { get; set; }
#nullable restore
#else
        public string BatteryVoltageUnit { get; set; }
#endif
        /// <summary>DC module current</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DcCurrent { get; set; }
#nullable restore
#else
        public string DcCurrent { get; set; }
#endif
        /// <summary>DC module current - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DcCurrentUnit { get; set; }
#nullable restore
#else
        public string DcCurrentUnit { get; set; }
#endif
        /// <summary>DC module power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DcPower { get; set; }
#nullable restore
#else
        public string DcPower { get; set; }
#endif
        /// <summary>DC module power unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DcPowerUnit { get; set; }
#nullable restore
#else
        public string DcPowerUnit { get; set; }
#endif
        /// <summary>DC module status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DcStatus { get; set; }
#nullable restore
#else
        public string DcStatus { get; set; }
#endif
        /// <summary>DC module voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DcVoltage { get; set; }
#nullable restore
#else
        public string DcVoltage { get; set; }
#endif
        /// <summary>DC module voltage - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DcVoltageUnit { get; set; }
#nullable restore
#else
        public string DcVoltageUnit { get; set; }
#endif
        /// <summary>Power grid frequency</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GridFrequency { get; set; }
#nullable restore
#else
        public string GridFrequency { get; set; }
#endif
        /// <summary>Power grid frequency - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GridFrequencyUnit { get; set; }
#nullable restore
#else
        public string GridFrequencyUnit { get; set; }
#endif
        /// <summary>Grid power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GridPower { get; set; }
#nullable restore
#else
        public string GridPower { get; set; }
#endif
        /// <summary>Grid power - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GridPowerUnit { get; set; }
#nullable restore
#else
        public string GridPowerUnit { get; set; }
#endif
        /// <summary>Power grid status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GridStatus { get; set; }
#nullable restore
#else
        public string GridStatus { get; set; }
#endif
        /// <summary>Power grid status - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GridStatusUnit { get; set; }
#nullable restore
#else
        public string GridStatusUnit { get; set; }
#endif
        /// <summary>Output current of three-phase/single-phase A power grid</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L1Current { get; set; }
#nullable restore
#else
        public string L1Current { get; set; }
#endif
        /// <summary>Output current of three-phase/single-phase A power grid - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L1CurrentUnit { get; set; }
#nullable restore
#else
        public string L1CurrentUnit { get; set; }
#endif
        /// <summary>Phase A grid voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L1LineVoltage { get; set; }
#nullable restore
#else
        public string L1LineVoltage { get; set; }
#endif
        /// <summary>Phase A grid voltage - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L1LineVoltageUnit { get; set; }
#nullable restore
#else
        public string L1LineVoltageUnit { get; set; }
#endif
        /// <summary>Output power of three-phase/single-phase A power grid</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L1Power { get; set; }
#nullable restore
#else
        public string L1Power { get; set; }
#endif
        /// <summary>Power factor of Phase A</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L1PowerFactor { get; set; }
#nullable restore
#else
        public string L1PowerFactor { get; set; }
#endif
        /// <summary>Phase A power factor - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L1PowerFactorUnit { get; set; }
#nullable restore
#else
        public string L1PowerFactorUnit { get; set; }
#endif
        /// <summary>Output power of three-phase/single-phase A power grid - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L1PowerUnit { get; set; }
#nullable restore
#else
        public string L1PowerUnit { get; set; }
#endif
        /// <summary>Three-phase/single-phase A grid voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L1Voltage { get; set; }
#nullable restore
#else
        public string L1Voltage { get; set; }
#endif
        /// <summary>Three-phase/single-phase A grid voltage - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L1VoltageUnit { get; set; }
#nullable restore
#else
        public string L1VoltageUnit { get; set; }
#endif
        /// <summary>Three-phase B power grid output current</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L2Current { get; set; }
#nullable restore
#else
        public string L2Current { get; set; }
#endif
        /// <summary>Three-phase B power grid output current - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L2CurrentUnit { get; set; }
#nullable restore
#else
        public string L2CurrentUnit { get; set; }
#endif
        /// <summary>Grid voltage of Phase B</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L2LineVoltage { get; set; }
#nullable restore
#else
        public string L2LineVoltage { get; set; }
#endif
        /// <summary>Phase B grid voltage - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L2LineVoltageUnit { get; set; }
#nullable restore
#else
        public string L2LineVoltageUnit { get; set; }
#endif
        /// <summary>Output power of three-phase B power grid</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L2Power { get; set; }
#nullable restore
#else
        public string L2Power { get; set; }
#endif
        /// <summary>Power factor of Phase B</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L2PowerFactor { get; set; }
#nullable restore
#else
        public string L2PowerFactor { get; set; }
#endif
        /// <summary>Power factor of Phase B</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L2PowerFactorUnit { get; set; }
#nullable restore
#else
        public string L2PowerFactorUnit { get; set; }
#endif
        /// <summary>Three-phase B power grid output power - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L2PowerUnit { get; set; }
#nullable restore
#else
        public string L2PowerUnit { get; set; }
#endif
        /// <summary>Three-phase B grid voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L2Voltage { get; set; }
#nullable restore
#else
        public string L2Voltage { get; set; }
#endif
        /// <summary>Three-phase B grid voltage - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L2VoltageUnit { get; set; }
#nullable restore
#else
        public string L2VoltageUnit { get; set; }
#endif
        /// <summary>Three-phase C power grid output current</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L3Current { get; set; }
#nullable restore
#else
        public string L3Current { get; set; }
#endif
        /// <summary>Three-phase C power grid output current - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L3CurrentUnit { get; set; }
#nullable restore
#else
        public string L3CurrentUnit { get; set; }
#endif
        /// <summary>Phase C grid voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L3LineVoltage { get; set; }
#nullable restore
#else
        public string L3LineVoltage { get; set; }
#endif
        /// <summary>Phase C grid voltage - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L3LineVoltageUnit { get; set; }
#nullable restore
#else
        public string L3LineVoltageUnit { get; set; }
#endif
        /// <summary>Output power of three-phase C power grid</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L3Power { get; set; }
#nullable restore
#else
        public string L3Power { get; set; }
#endif
        /// <summary>Power factor of Phase C</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L3PowerFactor { get; set; }
#nullable restore
#else
        public string L3PowerFactor { get; set; }
#endif
        /// <summary>C-phase power factor - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L3PowerFactorUnit { get; set; }
#nullable restore
#else
        public string L3PowerFactorUnit { get; set; }
#endif
        /// <summary>Three-phase C power grid output power - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L3PowerUnit { get; set; }
#nullable restore
#else
        public string L3PowerUnit { get; set; }
#endif
        /// <summary>Three-phase C power grid output voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L3Voltage { get; set; }
#nullable restore
#else
        public string L3Voltage { get; set; }
#endif
        /// <summary>Three-phase C power grid output voltage - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? L3VoltageUnit { get; set; }
#nullable restore
#else
        public string L3VoltageUnit { get; set; }
#endif
        /// <summary>Number of MPPT channels</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MpptNum { get; set; }
#nullable restore
#else
        public string MpptNum { get; set; }
#endif
        /// <summary>Number of MPPT channels - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MpptNumUnit { get; set; }
#nullable restore
#else
        public string MpptNumUnit { get; set; }
#endif
        /// <summary>PV INPUT POWER</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Ppv { get; set; }
#nullable restore
#else
        public string Ppv { get; set; }
#endif
        /// <summary>pv input power - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PpvUnit { get; set; }
#nullable restore
#else
        public string PpvUnit { get; set; }
#endif
        /// <summary>Input power of photovoltaic inverter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PvInverterInputPower { get; set; }
#nullable restore
#else
        public string PvInverterInputPower { get; set; }
#endif
        /// <summary>Input power unit of photovoltaic inverter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PvInverterInputPowerUnit { get; set; }
#nullable restore
#else
        public string PvInverterInputPowerUnit { get; set; }
#endif
        /// <summary>Total power factor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalPowerFactor { get; set; }
#nullable restore
#else
        public string TotalPowerFactor { get; set; }
#endif
        /// <summary>Total power factor - unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalPowerFactorUnit { get; set; }
#nullable restore
#else
        public string TotalPowerFactorUnit { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.Models.ResponseOpenApiParallelRealtimeDto"/> and sets the default values.
        /// </summary>
        public ResponseOpenApiParallelRealtimeDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DynessConnector.Client.Models.ResponseOpenApiParallelRealtimeDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DynessConnector.Client.Models.ResponseOpenApiParallelRealtimeDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DynessConnector.Client.Models.ResponseOpenApiParallelRealtimeDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "batteryCurrent", n => { BatteryCurrent = n.GetStringValue(); } },
                { "batteryCurrentUnit", n => { BatteryCurrentUnit = n.GetStringValue(); } },
                { "batteryPower", n => { BatteryPower = n.GetStringValue(); } },
                { "batteryPowerUnit", n => { BatteryPowerUnit = n.GetStringValue(); } },
                { "batterySoc", n => { BatterySoc = n.GetStringValue(); } },
                { "batterySocUnit", n => { BatterySocUnit = n.GetStringValue(); } },
                { "batteryStatus", n => { BatteryStatus = n.GetStringValue(); } },
                { "batteryVoltage", n => { BatteryVoltage = n.GetStringValue(); } },
                { "batteryVoltageUnit", n => { BatteryVoltageUnit = n.GetStringValue(); } },
                { "dcCurrent", n => { DcCurrent = n.GetStringValue(); } },
                { "dcCurrentUnit", n => { DcCurrentUnit = n.GetStringValue(); } },
                { "dcPower", n => { DcPower = n.GetStringValue(); } },
                { "dcPowerUnit", n => { DcPowerUnit = n.GetStringValue(); } },
                { "dcStatus", n => { DcStatus = n.GetStringValue(); } },
                { "dcVoltage", n => { DcVoltage = n.GetStringValue(); } },
                { "dcVoltageUnit", n => { DcVoltageUnit = n.GetStringValue(); } },
                { "gridFrequency", n => { GridFrequency = n.GetStringValue(); } },
                { "gridFrequencyUnit", n => { GridFrequencyUnit = n.GetStringValue(); } },
                { "gridPower", n => { GridPower = n.GetStringValue(); } },
                { "gridPowerUnit", n => { GridPowerUnit = n.GetStringValue(); } },
                { "gridStatus", n => { GridStatus = n.GetStringValue(); } },
                { "gridStatusUnit", n => { GridStatusUnit = n.GetStringValue(); } },
                { "l1Current", n => { L1Current = n.GetStringValue(); } },
                { "l1CurrentUnit", n => { L1CurrentUnit = n.GetStringValue(); } },
                { "l1LineVoltage", n => { L1LineVoltage = n.GetStringValue(); } },
                { "l1LineVoltageUnit", n => { L1LineVoltageUnit = n.GetStringValue(); } },
                { "l1Power", n => { L1Power = n.GetStringValue(); } },
                { "l1PowerFactor", n => { L1PowerFactor = n.GetStringValue(); } },
                { "l1PowerFactorUnit", n => { L1PowerFactorUnit = n.GetStringValue(); } },
                { "l1PowerUnit", n => { L1PowerUnit = n.GetStringValue(); } },
                { "l1Voltage", n => { L1Voltage = n.GetStringValue(); } },
                { "l1VoltageUnit", n => { L1VoltageUnit = n.GetStringValue(); } },
                { "l2Current", n => { L2Current = n.GetStringValue(); } },
                { "l2CurrentUnit", n => { L2CurrentUnit = n.GetStringValue(); } },
                { "l2LineVoltage", n => { L2LineVoltage = n.GetStringValue(); } },
                { "l2LineVoltageUnit", n => { L2LineVoltageUnit = n.GetStringValue(); } },
                { "l2Power", n => { L2Power = n.GetStringValue(); } },
                { "l2PowerFactor", n => { L2PowerFactor = n.GetStringValue(); } },
                { "l2PowerFactorUnit", n => { L2PowerFactorUnit = n.GetStringValue(); } },
                { "l2PowerUnit", n => { L2PowerUnit = n.GetStringValue(); } },
                { "l2Voltage", n => { L2Voltage = n.GetStringValue(); } },
                { "l2VoltageUnit", n => { L2VoltageUnit = n.GetStringValue(); } },
                { "l3Current", n => { L3Current = n.GetStringValue(); } },
                { "l3CurrentUnit", n => { L3CurrentUnit = n.GetStringValue(); } },
                { "l3LineVoltage", n => { L3LineVoltage = n.GetStringValue(); } },
                { "l3LineVoltageUnit", n => { L3LineVoltageUnit = n.GetStringValue(); } },
                { "l3Power", n => { L3Power = n.GetStringValue(); } },
                { "l3PowerFactor", n => { L3PowerFactor = n.GetStringValue(); } },
                { "l3PowerFactorUnit", n => { L3PowerFactorUnit = n.GetStringValue(); } },
                { "l3PowerUnit", n => { L3PowerUnit = n.GetStringValue(); } },
                { "l3Voltage", n => { L3Voltage = n.GetStringValue(); } },
                { "l3VoltageUnit", n => { L3VoltageUnit = n.GetStringValue(); } },
                { "mpptNum", n => { MpptNum = n.GetStringValue(); } },
                { "mpptNumUnit", n => { MpptNumUnit = n.GetStringValue(); } },
                { "ppv", n => { Ppv = n.GetStringValue(); } },
                { "ppvUnit", n => { PpvUnit = n.GetStringValue(); } },
                { "pvInverterInputPower", n => { PvInverterInputPower = n.GetStringValue(); } },
                { "pvInverterInputPowerUnit", n => { PvInverterInputPowerUnit = n.GetStringValue(); } },
                { "totalPowerFactor", n => { TotalPowerFactor = n.GetStringValue(); } },
                { "totalPowerFactorUnit", n => { TotalPowerFactorUnit = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("batteryCurrent", BatteryCurrent);
            writer.WriteStringValue("batteryCurrentUnit", BatteryCurrentUnit);
            writer.WriteStringValue("batteryPower", BatteryPower);
            writer.WriteStringValue("batteryPowerUnit", BatteryPowerUnit);
            writer.WriteStringValue("batterySoc", BatterySoc);
            writer.WriteStringValue("batterySocUnit", BatterySocUnit);
            writer.WriteStringValue("batteryStatus", BatteryStatus);
            writer.WriteStringValue("batteryVoltage", BatteryVoltage);
            writer.WriteStringValue("batteryVoltageUnit", BatteryVoltageUnit);
            writer.WriteStringValue("dcCurrent", DcCurrent);
            writer.WriteStringValue("dcCurrentUnit", DcCurrentUnit);
            writer.WriteStringValue("dcPower", DcPower);
            writer.WriteStringValue("dcPowerUnit", DcPowerUnit);
            writer.WriteStringValue("dcStatus", DcStatus);
            writer.WriteStringValue("dcVoltage", DcVoltage);
            writer.WriteStringValue("dcVoltageUnit", DcVoltageUnit);
            writer.WriteStringValue("gridFrequency", GridFrequency);
            writer.WriteStringValue("gridFrequencyUnit", GridFrequencyUnit);
            writer.WriteStringValue("gridPower", GridPower);
            writer.WriteStringValue("gridPowerUnit", GridPowerUnit);
            writer.WriteStringValue("gridStatus", GridStatus);
            writer.WriteStringValue("gridStatusUnit", GridStatusUnit);
            writer.WriteStringValue("l1Current", L1Current);
            writer.WriteStringValue("l1CurrentUnit", L1CurrentUnit);
            writer.WriteStringValue("l1LineVoltage", L1LineVoltage);
            writer.WriteStringValue("l1LineVoltageUnit", L1LineVoltageUnit);
            writer.WriteStringValue("l1Power", L1Power);
            writer.WriteStringValue("l1PowerFactor", L1PowerFactor);
            writer.WriteStringValue("l1PowerFactorUnit", L1PowerFactorUnit);
            writer.WriteStringValue("l1PowerUnit", L1PowerUnit);
            writer.WriteStringValue("l1Voltage", L1Voltage);
            writer.WriteStringValue("l1VoltageUnit", L1VoltageUnit);
            writer.WriteStringValue("l2Current", L2Current);
            writer.WriteStringValue("l2CurrentUnit", L2CurrentUnit);
            writer.WriteStringValue("l2LineVoltage", L2LineVoltage);
            writer.WriteStringValue("l2LineVoltageUnit", L2LineVoltageUnit);
            writer.WriteStringValue("l2Power", L2Power);
            writer.WriteStringValue("l2PowerFactor", L2PowerFactor);
            writer.WriteStringValue("l2PowerFactorUnit", L2PowerFactorUnit);
            writer.WriteStringValue("l2PowerUnit", L2PowerUnit);
            writer.WriteStringValue("l2Voltage", L2Voltage);
            writer.WriteStringValue("l2VoltageUnit", L2VoltageUnit);
            writer.WriteStringValue("l3Current", L3Current);
            writer.WriteStringValue("l3CurrentUnit", L3CurrentUnit);
            writer.WriteStringValue("l3LineVoltage", L3LineVoltage);
            writer.WriteStringValue("l3LineVoltageUnit", L3LineVoltageUnit);
            writer.WriteStringValue("l3Power", L3Power);
            writer.WriteStringValue("l3PowerFactor", L3PowerFactor);
            writer.WriteStringValue("l3PowerFactorUnit", L3PowerFactorUnit);
            writer.WriteStringValue("l3PowerUnit", L3PowerUnit);
            writer.WriteStringValue("l3Voltage", L3Voltage);
            writer.WriteStringValue("l3VoltageUnit", L3VoltageUnit);
            writer.WriteStringValue("mpptNum", MpptNum);
            writer.WriteStringValue("mpptNumUnit", MpptNumUnit);
            writer.WriteStringValue("ppv", Ppv);
            writer.WriteStringValue("ppvUnit", PpvUnit);
            writer.WriteStringValue("pvInverterInputPower", PvInverterInputPower);
            writer.WriteStringValue("pvInverterInputPowerUnit", PvInverterInputPowerUnit);
            writer.WriteStringValue("totalPowerFactor", TotalPowerFactor);
            writer.WriteStringValue("totalPowerFactorUnit", TotalPowerFactorUnit);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
