// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DynessConnector.Client.Models
{
    /// <summary>
    /// list of energy storage devices
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResponseStationDeviceJuniorDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>battery category（0 other，1 Raymond-juniorbox，2 Raymond household storage low pressure，3 Raymond battery cluster，4 solis）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryCategory { get; set; }
#nullable restore
#else
        public string BatteryCategory { get; set; }
#endif
        /// <summary>collector sn</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CollectorSn { get; set; }
#nullable restore
#else
        public string CollectorSn { get; set; }
#endif
        /// <summary>create time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreateTime { get; set; }
#nullable restore
#else
        public string CreateTime { get; set; }
#endif
        /// <summary>device communication status（online、offline、breakdown）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceCommunicationStatus { get; set; }
#nullable restore
#else
        public string DeviceCommunicationStatus { get; set; }
#endif
        /// <summary>device communication status code（1、2、3）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceCommunicationStatusCode { get; set; }
#nullable restore
#else
        public string DeviceCommunicationStatusCode { get; set; }
#endif
        /// <summary>device model code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceModelCode { get; set; }
#nullable restore
#else
        public string DeviceModelCode { get; set; }
#endif
        /// <summary>device model name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceModelName { get; set; }
#nullable restore
#else
        public string DeviceModelName { get; set; }
#endif
        /// <summary>device name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceName { get; set; }
#nullable restore
#else
        public string DeviceName { get; set; }
#endif
        /// <summary>energy storage equipment sn</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceSn { get; set; }
#nullable restore
#else
        public string DeviceSn { get; set; }
#endif
        /// <summary>factory</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Factory { get; set; }
#nullable restore
#else
        public string Factory { get; set; }
#endif
        /// <summary>firmware version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirmwareVersion { get; set; }
#nullable restore
#else
        public string FirmwareVersion { get; set; }
#endif
        /// <summary>master slave flag（master、slave）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MasterSlaveStatus { get; set; }
#nullable restore
#else
        public string MasterSlaveStatus { get; set; }
#endif
        /// <summary>operation permission（0：view 1：controllable 2：owner 3：super management 4:operation and maintenance）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OperationPermission { get; set; }
#nullable restore
#else
        public string OperationPermission { get; set; }
#endif
        /// <summary>model code of the parent device</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentCode { get; set; }
#nullable restore
#else
        public string ParentCode { get; set; }
#endif
        /// <summary>model name of the parent device</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentName { get; set; }
#nullable restore
#else
        public string ParentName { get; set; }
#endif
        /// <summary>station position</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Position { get; set; }
#nullable restore
#else
        public string Position { get; set; }
#endif
        /// <summary>product type（0 other，1 battery system，2 Inverter，3 Industry and commerce）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductType { get; set; }
#nullable restore
#else
        public string ProductType { get; set; }
#endif
        /// <summary>station id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StationId { get; set; }
#nullable restore
#else
        public string StationId { get; set; }
#endif
        /// <summary>station name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StationName { get; set; }
#nullable restore
#else
        public string StationName { get; set; }
#endif
        /// <summary>station type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StationType { get; set; }
#nullable restore
#else
        public string StationType { get; set; }
#endif
        /// <summary>system type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SystemType { get; set; }
#nullable restore
#else
        public string SystemType { get; set; }
#endif
        /// <summary>device work status：standby（wait_mode）、run（run_mode）、fault（fault_mode）、check（check_mode）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkStatus { get; set; }
#nullable restore
#else
        public string WorkStatus { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.Models.ResponseStationDeviceJuniorDto"/> and sets the default values.
        /// </summary>
        public ResponseStationDeviceJuniorDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DynessConnector.Client.Models.ResponseStationDeviceJuniorDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DynessConnector.Client.Models.ResponseStationDeviceJuniorDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DynessConnector.Client.Models.ResponseStationDeviceJuniorDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "batteryCategory", n => { BatteryCategory = n.GetStringValue(); } },
                { "collectorSn", n => { CollectorSn = n.GetStringValue(); } },
                { "createTime", n => { CreateTime = n.GetStringValue(); } },
                { "deviceCommunicationStatus", n => { DeviceCommunicationStatus = n.GetStringValue(); } },
                { "deviceCommunicationStatusCode", n => { DeviceCommunicationStatusCode = n.GetStringValue(); } },
                { "deviceModelCode", n => { DeviceModelCode = n.GetStringValue(); } },
                { "deviceModelName", n => { DeviceModelName = n.GetStringValue(); } },
                { "deviceName", n => { DeviceName = n.GetStringValue(); } },
                { "deviceSn", n => { DeviceSn = n.GetStringValue(); } },
                { "factory", n => { Factory = n.GetStringValue(); } },
                { "firmwareVersion", n => { FirmwareVersion = n.GetStringValue(); } },
                { "masterSlaveStatus", n => { MasterSlaveStatus = n.GetStringValue(); } },
                { "operationPermission", n => { OperationPermission = n.GetStringValue(); } },
                { "parentCode", n => { ParentCode = n.GetStringValue(); } },
                { "parentName", n => { ParentName = n.GetStringValue(); } },
                { "position", n => { Position = n.GetStringValue(); } },
                { "productType", n => { ProductType = n.GetStringValue(); } },
                { "stationId", n => { StationId = n.GetStringValue(); } },
                { "stationName", n => { StationName = n.GetStringValue(); } },
                { "stationType", n => { StationType = n.GetStringValue(); } },
                { "systemType", n => { SystemType = n.GetStringValue(); } },
                { "workStatus", n => { WorkStatus = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("batteryCategory", BatteryCategory);
            writer.WriteStringValue("collectorSn", CollectorSn);
            writer.WriteStringValue("createTime", CreateTime);
            writer.WriteStringValue("deviceCommunicationStatus", DeviceCommunicationStatus);
            writer.WriteStringValue("deviceCommunicationStatusCode", DeviceCommunicationStatusCode);
            writer.WriteStringValue("deviceModelCode", DeviceModelCode);
            writer.WriteStringValue("deviceModelName", DeviceModelName);
            writer.WriteStringValue("deviceName", DeviceName);
            writer.WriteStringValue("deviceSn", DeviceSn);
            writer.WriteStringValue("factory", Factory);
            writer.WriteStringValue("firmwareVersion", FirmwareVersion);
            writer.WriteStringValue("masterSlaveStatus", MasterSlaveStatus);
            writer.WriteStringValue("operationPermission", OperationPermission);
            writer.WriteStringValue("parentCode", ParentCode);
            writer.WriteStringValue("parentName", ParentName);
            writer.WriteStringValue("position", Position);
            writer.WriteStringValue("productType", ProductType);
            writer.WriteStringValue("stationId", StationId);
            writer.WriteStringValue("stationName", StationName);
            writer.WriteStringValue("stationType", StationType);
            writer.WriteStringValue("systemType", SystemType);
            writer.WriteStringValue("workStatus", WorkStatus);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
