// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DynessConnector.Client.Models
{
    /// <summary>
    /// energy storage devices details
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResponseDeviceJuniorDetailDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Battery classification (0 Others, 1 Raymond junior, 2 Raymond Household Storage Low Voltage, 3 Raymond Battery Cluster, 4 Jinlang,5 Commercial and Industrial)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryCategory { get; set; }
#nullable restore
#else
        public string BatteryCategory { get; set; }
#endif
        /// <summary>brand</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Brand { get; set; }
#nullable restore
#else
        public string Brand { get; set; }
#endif
        /// <summary>collector sn</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CollectorSn { get; set; }
#nullable restore
#else
        public string CollectorSn { get; set; }
#endif
        /// <summary>create time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreateTime { get; set; }
#nullable restore
#else
        public string CreateTime { get; set; }
#endif
        /// <summary>Rated current</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Current { get; set; }
#nullable restore
#else
        public string Current { get; set; }
#endif
        /// <summary>Rated current unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrentUnit { get; set; }
#nullable restore
#else
        public string CurrentUnit { get; set; }
#endif
        /// <summary>data update time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DataUpdateTime { get; set; }
#nullable restore
#else
        public string DataUpdateTime { get; set; }
#endif
        /// <summary>device communication status（online、offline、breakdown）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceCommunicationStatus { get; set; }
#nullable restore
#else
        public string DeviceCommunicationStatus { get; set; }
#endif
        /// <summary>device communication status（1、2、3）</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceCommunicationStatusCode { get; set; }
#nullable restore
#else
        public string DeviceCommunicationStatusCode { get; set; }
#endif
        /// <summary>device model code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceModelCode { get; set; }
#nullable restore
#else
        public string DeviceModelCode { get; set; }
#endif
        /// <summary>device model name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceModelName { get; set; }
#nullable restore
#else
        public string DeviceModelName { get; set; }
#endif
        /// <summary>device name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceName { get; set; }
#nullable restore
#else
        public string DeviceName { get; set; }
#endif
        /// <summary>device sn</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceSn { get; set; }
#nullable restore
#else
        public string DeviceSn { get; set; }
#endif
        /// <summary>device type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceType { get; set; }
#nullable restore
#else
        public string DeviceType { get; set; }
#endif
        /// <summary>device type code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceTypeCode { get; set; }
#nullable restore
#else
        public string DeviceTypeCode { get; set; }
#endif
        /// <summary>Rated energy (Unit: kWh)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Energy { get; set; }
#nullable restore
#else
        public string Energy { get; set; }
#endif
        /// <summary>factory</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Factory { get; set; }
#nullable restore
#else
        public string Factory { get; set; }
#endif
        /// <summary>firmware version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirmwareVersion { get; set; }
#nullable restore
#else
        public string FirmwareVersion { get; set; }
#endif
        /// <summary>Avatar picture address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImgAddress { get; set; }
#nullable restore
#else
        public string ImgAddress { get; set; }
#endif
        /// <summary>Installed capacity (kWh)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InstalledPower { get; set; }
#nullable restore
#else
        public string InstalledPower { get; set; }
#endif
        /// <summary>1 master；2 salve</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MasterSlaveStatus { get; set; }
#nullable restore
#else
        public string MasterSlaveStatus { get; set; }
#endif
        /// <summary>Associate with SN of shelly meter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MeterSn { get; set; }
#nullable restore
#else
        public string MeterSn { get; set; }
#endif
        /// <summary>mppt version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MpptVersion { get; set; }
#nullable restore
#else
        public string MpptVersion { get; set; }
#endif
        /// <summary>mppt upgrade result</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OtaMpptResult { get; set; }
#nullable restore
#else
        public string OtaMpptResult { get; set; }
#endif
        /// <summary>ota result</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OtaResult { get; set; }
#nullable restore
#else
        public string OtaResult { get; set; }
#endif
        /// <summary>station position</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Position { get; set; }
#nullable restore
#else
        public string Position { get; set; }
#endif
        /// <summary>Product types (0 Others, 1 Battery system, 2 Inverters, 3 Commercial and Industrial)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductType { get; set; }
#nullable restore
#else
        public string ProductType { get; set; }
#endif
        /// <summary>station sn</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StationId { get; set; }
#nullable restore
#else
        public string StationId { get; set; }
#endif
        /// <summary>station name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StationName { get; set; }
#nullable restore
#else
        public string StationName { get; set; }
#endif
        /// <summary>station type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StationType { get; set; }
#nullable restore
#else
        public string StationType { get; set; }
#endif
        /// <summary>system type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SystemType { get; set; }
#nullable restore
#else
        public string SystemType { get; set; }
#endif
        /// <summary>rated voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Voltage { get; set; }
#nullable restore
#else
        public string Voltage { get; set; }
#endif
        /// <summary>Rated voltage unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VoltageUnit { get; set; }
#nullable restore
#else
        public string VoltageUnit { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.Models.ResponseDeviceJuniorDetailDto"/> and sets the default values.
        /// </summary>
        public ResponseDeviceJuniorDetailDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DynessConnector.Client.Models.ResponseDeviceJuniorDetailDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DynessConnector.Client.Models.ResponseDeviceJuniorDetailDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DynessConnector.Client.Models.ResponseDeviceJuniorDetailDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "batteryCategory", n => { BatteryCategory = n.GetStringValue(); } },
                { "brand", n => { Brand = n.GetStringValue(); } },
                { "collectorSn", n => { CollectorSn = n.GetStringValue(); } },
                { "createTime", n => { CreateTime = n.GetStringValue(); } },
                { "current", n => { Current = n.GetStringValue(); } },
                { "currentUnit", n => { CurrentUnit = n.GetStringValue(); } },
                { "dataUpdateTime", n => { DataUpdateTime = n.GetStringValue(); } },
                { "deviceCommunicationStatus", n => { DeviceCommunicationStatus = n.GetStringValue(); } },
                { "deviceCommunicationStatusCode", n => { DeviceCommunicationStatusCode = n.GetStringValue(); } },
                { "deviceModelCode", n => { DeviceModelCode = n.GetStringValue(); } },
                { "deviceModelName", n => { DeviceModelName = n.GetStringValue(); } },
                { "deviceName", n => { DeviceName = n.GetStringValue(); } },
                { "deviceSn", n => { DeviceSn = n.GetStringValue(); } },
                { "deviceType", n => { DeviceType = n.GetStringValue(); } },
                { "deviceTypeCode", n => { DeviceTypeCode = n.GetStringValue(); } },
                { "energy", n => { Energy = n.GetStringValue(); } },
                { "factory", n => { Factory = n.GetStringValue(); } },
                { "firmwareVersion", n => { FirmwareVersion = n.GetStringValue(); } },
                { "imgAddress", n => { ImgAddress = n.GetStringValue(); } },
                { "installedPower", n => { InstalledPower = n.GetStringValue(); } },
                { "masterSlaveStatus", n => { MasterSlaveStatus = n.GetStringValue(); } },
                { "meterSn", n => { MeterSn = n.GetStringValue(); } },
                { "mpptVersion", n => { MpptVersion = n.GetStringValue(); } },
                { "otaMpptResult", n => { OtaMpptResult = n.GetStringValue(); } },
                { "otaResult", n => { OtaResult = n.GetStringValue(); } },
                { "position", n => { Position = n.GetStringValue(); } },
                { "productType", n => { ProductType = n.GetStringValue(); } },
                { "stationId", n => { StationId = n.GetStringValue(); } },
                { "stationName", n => { StationName = n.GetStringValue(); } },
                { "stationType", n => { StationType = n.GetStringValue(); } },
                { "systemType", n => { SystemType = n.GetStringValue(); } },
                { "voltage", n => { Voltage = n.GetStringValue(); } },
                { "voltageUnit", n => { VoltageUnit = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("batteryCategory", BatteryCategory);
            writer.WriteStringValue("brand", Brand);
            writer.WriteStringValue("collectorSn", CollectorSn);
            writer.WriteStringValue("createTime", CreateTime);
            writer.WriteStringValue("current", Current);
            writer.WriteStringValue("currentUnit", CurrentUnit);
            writer.WriteStringValue("dataUpdateTime", DataUpdateTime);
            writer.WriteStringValue("deviceCommunicationStatus", DeviceCommunicationStatus);
            writer.WriteStringValue("deviceCommunicationStatusCode", DeviceCommunicationStatusCode);
            writer.WriteStringValue("deviceModelCode", DeviceModelCode);
            writer.WriteStringValue("deviceModelName", DeviceModelName);
            writer.WriteStringValue("deviceName", DeviceName);
            writer.WriteStringValue("deviceSn", DeviceSn);
            writer.WriteStringValue("deviceType", DeviceType);
            writer.WriteStringValue("deviceTypeCode", DeviceTypeCode);
            writer.WriteStringValue("energy", Energy);
            writer.WriteStringValue("factory", Factory);
            writer.WriteStringValue("firmwareVersion", FirmwareVersion);
            writer.WriteStringValue("imgAddress", ImgAddress);
            writer.WriteStringValue("installedPower", InstalledPower);
            writer.WriteStringValue("masterSlaveStatus", MasterSlaveStatus);
            writer.WriteStringValue("meterSn", MeterSn);
            writer.WriteStringValue("mpptVersion", MpptVersion);
            writer.WriteStringValue("otaMpptResult", OtaMpptResult);
            writer.WriteStringValue("otaResult", OtaResult);
            writer.WriteStringValue("position", Position);
            writer.WriteStringValue("productType", ProductType);
            writer.WriteStringValue("stationId", StationId);
            writer.WriteStringValue("stationName", StationName);
            writer.WriteStringValue("stationType", StationType);
            writer.WriteStringValue("systemType", SystemType);
            writer.WriteStringValue("voltage", Voltage);
            writer.WriteStringValue("voltageUnit", VoltageUnit);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
