// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DynessConnector.Client.Models
{
    /// <summary>
    /// Alarm query data
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResponseOpenApiAlarmPageDataDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The quantity of all data</summary>
        public long? AllCount { get; set; }
        /// <summary>The pageDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DynessConnector.Client.Models.ResponsePageResponseOpenApiAlarmPageDto? PageDate { get; set; }
#nullable restore
#else
        public global::DynessConnector.Client.Models.ResponsePageResponseOpenApiAlarmPageDto PageDate { get; set; }
#endif
        /// <summary>The number of read</summary>
        public long? ReadCount { get; set; }
        /// <summary>Unread quantity</summary>
        public long? UnReadCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.Models.ResponseOpenApiAlarmPageDataDto"/> and sets the default values.
        /// </summary>
        public ResponseOpenApiAlarmPageDataDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DynessConnector.Client.Models.ResponseOpenApiAlarmPageDataDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DynessConnector.Client.Models.ResponseOpenApiAlarmPageDataDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DynessConnector.Client.Models.ResponseOpenApiAlarmPageDataDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allCount", n => { AllCount = n.GetLongValue(); } },
                { "pageDate", n => { PageDate = n.GetObjectValue<global::DynessConnector.Client.Models.ResponsePageResponseOpenApiAlarmPageDto>(global::DynessConnector.Client.Models.ResponsePageResponseOpenApiAlarmPageDto.CreateFromDiscriminatorValue); } },
                { "readCount", n => { ReadCount = n.GetLongValue(); } },
                { "unReadCount", n => { UnReadCount = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("allCount", AllCount);
            writer.WriteObjectValue<global::DynessConnector.Client.Models.ResponsePageResponseOpenApiAlarmPageDto>("pageDate", PageDate);
            writer.WriteLongValue("readCount", ReadCount);
            writer.WriteLongValue("unReadCount", UnReadCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
