// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DynessConnector.Client.Models
{
    /// <summary>
    /// Alarm fault information
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResponseIgenFaultWarnDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Fault time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreateTime { get; set; }
#nullable restore
#else
        public string CreateTime { get; set; }
#endif
        /// <summary>Device SN</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceCode { get; set; }
#nullable restore
#else
        public string DeviceCode { get; set; }
#endif
        /// <summary>Event type (0: fault 1: alarm)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventType { get; set; }
#nullable restore
#else
        public string EventType { get; set; }
#endif
        /// <summary>Fault code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FaultCode { get; set; }
#nullable restore
#else
        public string FaultCode { get; set; }
#endif
        /// <summary>Fault content</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FaultContent { get; set; }
#nullable restore
#else
        public string FaultContent { get; set; }
#endif
        /// <summary>Fault temperature (celsius)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FaultEnvironment { get; set; }
#nullable restore
#else
        public string FaultEnvironment { get; set; }
#endif
        /// <summary>Fault temperature (fahrenheit)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FaultEnvironmentFahrenheit { get; set; }
#nullable restore
#else
        public string FaultEnvironmentFahrenheit { get; set; }
#endif
        /// <summary>Fault ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FaultId { get; set; }
#nullable restore
#else
        public string FaultId { get; set; }
#endif
        /// <summary>Fault type (0: system fault 1: machine fault 2: battery fault 3: battery warning)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FaultType { get; set; }
#nullable restore
#else
        public string FaultType { get; set; }
#endif
        /// <summary>Working status (0: Wait mode 1: On-grid mode 2: Off-grid mode 3: Fault mode 4: Flash mode 5: Check mode)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkState { get; set; }
#nullable restore
#else
        public string WorkState { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.Models.ResponseIgenFaultWarnDto"/> and sets the default values.
        /// </summary>
        public ResponseIgenFaultWarnDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DynessConnector.Client.Models.ResponseIgenFaultWarnDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DynessConnector.Client.Models.ResponseIgenFaultWarnDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DynessConnector.Client.Models.ResponseIgenFaultWarnDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createTime", n => { CreateTime = n.GetStringValue(); } },
                { "deviceCode", n => { DeviceCode = n.GetStringValue(); } },
                { "eventType", n => { EventType = n.GetStringValue(); } },
                { "faultCode", n => { FaultCode = n.GetStringValue(); } },
                { "faultContent", n => { FaultContent = n.GetStringValue(); } },
                { "faultEnvironment", n => { FaultEnvironment = n.GetStringValue(); } },
                { "faultEnvironmentFahrenheit", n => { FaultEnvironmentFahrenheit = n.GetStringValue(); } },
                { "faultId", n => { FaultId = n.GetStringValue(); } },
                { "faultType", n => { FaultType = n.GetStringValue(); } },
                { "workState", n => { WorkState = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("createTime", CreateTime);
            writer.WriteStringValue("deviceCode", DeviceCode);
            writer.WriteStringValue("eventType", EventType);
            writer.WriteStringValue("faultCode", FaultCode);
            writer.WriteStringValue("faultContent", FaultContent);
            writer.WriteStringValue("faultEnvironment", FaultEnvironment);
            writer.WriteStringValue("faultEnvironmentFahrenheit", FaultEnvironmentFahrenheit);
            writer.WriteStringValue("faultId", FaultId);
            writer.WriteStringValue("faultType", FaultType);
            writer.WriteStringValue("workState", WorkState);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
