// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DynessConnector.Client.Models
{
    /// <summary>
    /// Original data
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResponseAioOriginalDataDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Ac coupling power (item R)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AcCouplingPowerR { get; set; }
#nullable restore
#else
        public string AcCouplingPowerR { get; set; }
#endif
        /// <summary>Active power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActivePower { get; set; }
#nullable restore
#else
        public string ActivePower { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Alarm information</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlarmInformation { get; set; }
#nullable restore
#else
        public string AlarmInformation { get; set; }
#endif
        /// <summary>Apparent power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApparentPower { get; set; }
#nullable restore
#else
        public string ApparentPower { get; set; }
#endif
        /// <summary>ARM internal firmware version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ArmInnerVersion { get; set; }
#nullable restore
#else
        public string ArmInnerVersion { get; set; }
#endif
        /// <summary>ARM SVN version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ArmSvnVersion { get; set; }
#nullable restore
#else
        public string ArmSvnVersion { get; set; }
#endif
        /// <summary>ARM version number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ArmVersion { get; set; }
#nullable restore
#else
        public string ArmVersion { get; set; }
#endif
        /// <summary>Backup load (Unit: W)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BackupLoad { get; set; }
#nullable restore
#else
        public string BackupLoad { get; set; }
#endif
        /// <summary>Remaining battery power (unit: %)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryCapacity { get; set; }
#nullable restore
#else
        public string BatteryCapacity { get; set; }
#endif
        /// <summary>battery count</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryCount { get; set; }
#nullable restore
#else
        public string BatteryCount { get; set; }
#endif
        /// <summary>Battery current</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryCurrent { get; set; }
#nullable restore
#else
        public string BatteryCurrent { get; set; }
#endif
        /// <summary>Battery power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryPower { get; set; }
#nullable restore
#else
        public string BatteryPower { get; set; }
#endif
        /// <summary>Battery SOC</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatterySoc { get; set; }
#nullable restore
#else
        public string BatterySoc { get; set; }
#endif
        /// <summary>Battery SOH</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatterySoh { get; set; }
#nullable restore
#else
        public string BatterySoh { get; set; }
#endif
        /// <summary>Battery status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryStatus { get; set; }
#nullable restore
#else
        public string BatteryStatus { get; set; }
#endif
        /// <summary>Battery temperature</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryTemperature { get; set; }
#nullable restore
#else
        public string BatteryTemperature { get; set; }
#endif
        /// <summary>Battery voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryVoltage { get; set; }
#nullable restore
#else
        public string BatteryVoltage { get; set; }
#endif
        /// <summary>BMS communication status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BmsCommunication { get; set; }
#nullable restore
#else
        public string BmsCommunication { get; set; }
#endif
        /// <summary>BMS communication status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BmsCommunicationStatus { get; set; }
#nullable restore
#else
        public string BmsCommunicationStatus { get; set; }
#endif
        /// <summary>BOX communication status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BoxCommunication { get; set; }
#nullable restore
#else
        public string BoxCommunication { get; set; }
#endif
        /// <summary>BOX SVN version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BoxSvnVersion { get; set; }
#nullable restore
#else
        public string BoxSvnVersion { get; set; }
#endif
        /// <summary>BOX software version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BoxVersion { get; set; }
#nullable restore
#else
        public string BoxVersion { get; set; }
#endif
        /// <summary>bus voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusVoltage { get; set; }
#nullable restore
#else
        public string BusVoltage { get; set; }
#endif
        /// <summary>Buy electricity on the same day</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BuyEnergy { get; set; }
#nullable restore
#else
        public string BuyEnergy { get; set; }
#endif
        /// <summary>Battery charge capacity for the day (unit: kWh)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChargeEnergyDaily { get; set; }
#nullable restore
#else
        public string ChargeEnergyDaily { get; set; }
#endif
        /// <summary>Total battery charge capacity (unit: kWh)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChargeEnergyTotal { get; set; }
#nullable restore
#else
        public string ChargeEnergyTotal { get; set; }
#endif
        /// <summary>Rated power for battery charging (unit: W</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChargeRatedPower { get; set; }
#nullable restore
#else
        public string ChargeRatedPower { get; set; }
#endif
        /// <summary>Charging current limiting</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChargingLimitCurrent { get; set; }
#nullable restore
#else
        public string ChargingLimitCurrent { get; set; }
#endif
        /// <summary>Three-phase output of public power grid</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DynessConnector.Client.Models.DeviceOutModel>? CommonOutPut1 { get; set; }
#nullable restore
#else
        public List<global::DynessConnector.Client.Models.DeviceOutModel> CommonOutPut1 { get; set; }
#endif
        /// <summary>Communication protocol version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CommunicationProtocolVersion { get; set; }
#nullable restore
#else
        public string CommunicationProtocolVersion { get; set; }
#endif
        /// <summary>CT status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CtStatus { get; set; }
#nullable restore
#else
        public string CtStatus { get; set; }
#endif
        /// <summary>date time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateTime { get; set; }
#nullable restore
#else
        public string DateTime { get; set; }
#endif
        /// <summary>Daily electricity consumption</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DayElectricity { get; set; }
#nullable restore
#else
        public string DayElectricity { get; set; }
#endif
        /// <summary>Daily power generation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DayGeneration { get; set; }
#nullable restore
#else
        public string DayGeneration { get; set; }
#endif
        /// <summary>Device firmware version number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceHardwareVersion { get; set; }
#nullable restore
#else
        public string DeviceHardwareVersion { get; set; }
#endif
        /// <summary>Battery discharge capacity for the day (unit: kWh)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisChargeEnergyDaily { get; set; }
#nullable restore
#else
        public string DisChargeEnergyDaily { get; set; }
#endif
        /// <summary>Total battery discharge (unit: kWh)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisChargeEnergyTotal { get; set; }
#nullable restore
#else
        public string DisChargeEnergyTotal { get; set; }
#endif
        /// <summary>Discharge current limiting</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DischargeLimitCurrent { get; set; }
#nullable restore
#else
        public string DischargeLimitCurrent { get; set; }
#endif
        /// <summary>DSPS software version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Dsp1Version { get; set; }
#nullable restore
#else
        public string Dsp1Version { get; set; }
#endif
        /// <summary>DSP2 version number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Dsp2Version { get; set; }
#nullable restore
#else
        public string Dsp2Version { get; set; }
#endif
        /// <summary>Internal firmware version of DSP</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DspInnerVersion { get; set; }
#nullable restore
#else
        public string DspInnerVersion { get; set; }
#endif
        /// <summary>DSP Boot version number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DspSvnVersion { get; set; }
#nullable restore
#else
        public string DspSvnVersion { get; set; }
#endif
        /// <summary>Fault information</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? FaultInformations { get; set; }
#nullable restore
#else
        public List<string> FaultInformations { get; set; }
#endif
        /// <summary>Firmware version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirmwareVersion { get; set; }
#nullable restore
#else
        public string FirmwareVersion { get; set; }
#endif
        /// <summary>Power generation capacity</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GenerationPower { get; set; }
#nullable restore
#else
        public string GenerationPower { get; set; }
#endif
        /// <summary>Grid current phase R</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GridCurrentR { get; set; }
#nullable restore
#else
        public string GridCurrentR { get; set; }
#endif
        /// <summary>Grid current phase S</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GridCurrentS { get; set; }
#nullable restore
#else
        public string GridCurrentS { get; set; }
#endif
        /// <summary>Grid current phase T</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GridCurrentT { get; set; }
#nullable restore
#else
        public string GridCurrentT { get; set; }
#endif
        /// <summary>Grid-connected discharge depth</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GridDischargeDepth { get; set; }
#nullable restore
#else
        public string GridDischargeDepth { get; set; }
#endif
        /// <summary>Power grid frequency phase R</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GridFrequencyR { get; set; }
#nullable restore
#else
        public string GridFrequencyR { get; set; }
#endif
        /// <summary>Grid frequency phase S</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GridFrequencyS { get; set; }
#nullable restore
#else
        public string GridFrequencyS { get; set; }
#endif
        /// <summary>Power grid frequency phase T</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GridFrequencyT { get; set; }
#nullable restore
#else
        public string GridFrequencyT { get; set; }
#endif
        /// <summary>Grid power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GridPower { get; set; }
#nullable restore
#else
        public string GridPower { get; set; }
#endif
        /// <summary>power grid status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GridStatus { get; set; }
#nullable restore
#else
        public string GridStatus { get; set; }
#endif
        /// <summary>Heat dissipation temperature</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HeatDissipationTemperature { get; set; }
#nullable restore
#else
        public string HeatDissipationTemperature { get; set; }
#endif
        /// <summary>Household load (Unit: W)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HouseholdLoad { get; set; }
#nullable restore
#else
        public string HouseholdLoad { get; set; }
#endif
        /// <summary>Internal temperature</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InternalTemperature { get; set; }
#nullable restore
#else
        public string InternalTemperature { get; set; }
#endif
        /// <summary>Last update time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastUpdateTime { get; set; }
#nullable restore
#else
        public string LastUpdateTime { get; set; }
#endif
        /// <summary>Total load power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LoadPower { get; set; }
#nullable restore
#else
        public string LoadPower { get; set; }
#endif
        /// <summary>Manufacturer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Manufacturer { get; set; }
#nullable restore
#else
        public string Manufacturer { get; set; }
#endif
        /// <summary>Battery capacity</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaxLeadBatCapacity { get; set; }
#nullable restore
#else
        public string MaxLeadBatCapacity { get; set; }
#endif
        /// <summary>Electricity meter communication</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MeterCommunication { get; set; }
#nullable restore
#else
        public string MeterCommunication { get; set; }
#endif
        /// <summary>Electricity meter status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MeterStatus { get; set; }
#nullable restore
#else
        public string MeterStatus { get; set; }
#endif
        /// <summary>Module temperature</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModuleTemperature { get; set; }
#nullable restore
#else
        public string ModuleTemperature { get; set; }
#endif
        /// <summary>nbus voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NbusVoltage { get; set; }
#nullable restore
#else
        public string NbusVoltage { get; set; }
#endif
        /// <summary>Off-grid discharge depth</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OffGridDischargeDepth { get; set; }
#nullable restore
#else
        public string OffGridDischargeDepth { get; set; }
#endif
        /// <summary>Inverter three-phase output </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DynessConnector.Client.Models.DeviceOutModel>? OutPut1 { get; set; }
#nullable restore
#else
        public List<global::DynessConnector.Client.Models.DeviceOutModel> OutPut1 { get; set; }
#endif
        /// <summary>Output mode: 0: Single-phase 1: Three-phase four-wire system 2: Three-phase single-wire system 3: Two-phase three-wire system</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OutputMethod { get; set; }
#nullable restore
#else
        public string OutputMethod { get; set; }
#endif
        /// <summary>Grid-connected power limit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PowerLimit { get; set; }
#nullable restore
#else
        public string PowerLimit { get; set; }
#endif
        /// <summary>pv1 current</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pv1Current { get; set; }
#nullable restore
#else
        public string Pv1Current { get; set; }
#endif
        /// <summary>pv1 power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pv1Power { get; set; }
#nullable restore
#else
        public string Pv1Power { get; set; }
#endif
        /// <summary>pv1 status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pv1Status { get; set; }
#nullable restore
#else
        public string Pv1Status { get; set; }
#endif
        /// <summary>pv1 voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pv1Voltage { get; set; }
#nullable restore
#else
        public string Pv1Voltage { get; set; }
#endif
        /// <summary>pv2 current</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pv2Current { get; set; }
#nullable restore
#else
        public string Pv2Current { get; set; }
#endif
        /// <summary>pv2 power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pv2Power { get; set; }
#nullable restore
#else
        public string Pv2Power { get; set; }
#endif
        /// <summary>pv2 status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pv2Status { get; set; }
#nullable restore
#else
        public string Pv2Status { get; set; }
#endif
        /// <summary>pv2 voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pv2Voltage { get; set; }
#nullable restore
#else
        public string Pv2Voltage { get; set; }
#endif
        /// <summary>pv3 current</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pv3Current { get; set; }
#nullable restore
#else
        public string Pv3Current { get; set; }
#endif
        /// <summary>pv3 power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pv3Power { get; set; }
#nullable restore
#else
        public string Pv3Power { get; set; }
#endif
        /// <summary>pv3 status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pv3Status { get; set; }
#nullable restore
#else
        public string Pv3Status { get; set; }
#endif
        /// <summary>pv3 voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pv3Voltage { get; set; }
#nullable restore
#else
        public string Pv3Voltage { get; set; }
#endif
        /// <summary>pv4 current</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pv4Current { get; set; }
#nullable restore
#else
        public string Pv4Current { get; set; }
#endif
        /// <summary>pv4 power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pv4Power { get; set; }
#nullable restore
#else
        public string Pv4Power { get; set; }
#endif
        /// <summary>pv4 status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pv4Status { get; set; }
#nullable restore
#else
        public string Pv4Status { get; set; }
#endif
        /// <summary>pv4 voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pv4Voltage { get; set; }
#nullable restore
#else
        public string Pv4Voltage { get; set; }
#endif
        /// <summary>Photovoltaic power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PvPower { get; set; }
#nullable restore
#else
        public string PvPower { get; set; }
#endif
        /// <summary>Rated power of AC</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RatedPower { get; set; }
#nullable restore
#else
        public string RatedPower { get; set; }
#endif
        /// <summary>The rcurrent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Rcurrent { get; set; }
#nullable restore
#else
        public string Rcurrent { get; set; }
#endif
        /// <summary>Reactive power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReactivePower { get; set; }
#nullable restore
#else
        public string ReactivePower { get; set; }
#endif
        /// <summary>The rgridFrequency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RgridFrequency { get; set; }
#nullable restore
#else
        public string RgridFrequency { get; set; }
#endif
        /// <summary>The rpower property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Rpower { get; set; }
#nullable restore
#else
        public string Rpower { get; set; }
#endif
        /// <summary>The rspareCurrent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RspareCurrent { get; set; }
#nullable restore
#else
        public string RspareCurrent { get; set; }
#endif
        /// <summary>The rspareGridFrequency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RspareGridFrequency { get; set; }
#nullable restore
#else
        public string RspareGridFrequency { get; set; }
#endif
        /// <summary>The rsparePower property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RsparePower { get; set; }
#nullable restore
#else
        public string RsparePower { get; set; }
#endif
        /// <summary>The rspareVoltage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RspareVoltage { get; set; }
#nullable restore
#else
        public string RspareVoltage { get; set; }
#endif
        /// <summary>Operating mode</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RunModel { get; set; }
#nullable restore
#else
        public string RunModel { get; set; }
#endif
        /// <summary>The rvoltage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Rvoltage { get; set; }
#nullable restore
#else
        public string Rvoltage { get; set; }
#endif
        /// <summary>Countries with safety regulations</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SafetyCountry { get; set; }
#nullable restore
#else
        public string SafetyCountry { get; set; }
#endif
        /// <summary>Sell electricity on the same day</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SellEnergy { get; set; }
#nullable restore
#else
        public string SellEnergy { get; set; }
#endif
        /// <summary>SN</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sn { get; set; }
#nullable restore
#else
        public string Sn { get; set; }
#endif
        /// <summary>Backup power supply</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SparePower { get; set; }
#nullable restore
#else
        public string SparePower { get; set; }
#endif
        /// <summary>Standby three-phase output </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DynessConnector.Client.Models.DeviceOutModel>? StandByOutPut1 { get; set; }
#nullable restore
#else
        public List<global::DynessConnector.Client.Models.DeviceOutModel> StandByOutPut1 { get; set; }
#endif
        /// <summary>Cumulative purchased electricity</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalBuyEnergy { get; set; }
#nullable restore
#else
        public string TotalBuyEnergy { get; set; }
#endif
        /// <summary>Total electricity consumption</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalElectricity { get; set; }
#nullable restore
#else
        public string TotalElectricity { get; set; }
#endif
        /// <summary>Cumulative power generation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalGeneration { get; set; }
#nullable restore
#else
        public string TotalGeneration { get; set; }
#endif
        /// <summary>Cumulative electricity sales</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalSellEnergy { get; set; }
#nullable restore
#else
        public string TotalSellEnergy { get; set; }
#endif
        /// <summary>Host version number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>Working status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkStatus { get; set; }
#nullable restore
#else
        public string WorkStatus { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.Models.ResponseAioOriginalDataDto"/> and sets the default values.
        /// </summary>
        public ResponseAioOriginalDataDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DynessConnector.Client.Models.ResponseAioOriginalDataDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DynessConnector.Client.Models.ResponseAioOriginalDataDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DynessConnector.Client.Models.ResponseAioOriginalDataDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "acCouplingPowerR", n => { AcCouplingPowerR = n.GetStringValue(); } },
                { "activePower", n => { ActivePower = n.GetStringValue(); } },
                { "alarmInformation", n => { AlarmInformation = n.GetStringValue(); } },
                { "apparentPower", n => { ApparentPower = n.GetStringValue(); } },
                { "armInnerVersion", n => { ArmInnerVersion = n.GetStringValue(); } },
                { "armSvnVersion", n => { ArmSvnVersion = n.GetStringValue(); } },
                { "armVersion", n => { ArmVersion = n.GetStringValue(); } },
                { "backupLoad", n => { BackupLoad = n.GetStringValue(); } },
                { "batteryCapacity", n => { BatteryCapacity = n.GetStringValue(); } },
                { "batteryCount", n => { BatteryCount = n.GetStringValue(); } },
                { "batteryCurrent", n => { BatteryCurrent = n.GetStringValue(); } },
                { "batteryPower", n => { BatteryPower = n.GetStringValue(); } },
                { "batterySoc", n => { BatterySoc = n.GetStringValue(); } },
                { "batterySoh", n => { BatterySoh = n.GetStringValue(); } },
                { "batteryStatus", n => { BatteryStatus = n.GetStringValue(); } },
                { "batteryTemperature", n => { BatteryTemperature = n.GetStringValue(); } },
                { "batteryVoltage", n => { BatteryVoltage = n.GetStringValue(); } },
                { "bmsCommunication", n => { BmsCommunication = n.GetStringValue(); } },
                { "bmsCommunicationStatus", n => { BmsCommunicationStatus = n.GetStringValue(); } },
                { "boxCommunication", n => { BoxCommunication = n.GetStringValue(); } },
                { "boxSvnVersion", n => { BoxSvnVersion = n.GetStringValue(); } },
                { "boxVersion", n => { BoxVersion = n.GetStringValue(); } },
                { "busVoltage", n => { BusVoltage = n.GetStringValue(); } },
                { "buyEnergy", n => { BuyEnergy = n.GetStringValue(); } },
                { "chargeEnergyDaily", n => { ChargeEnergyDaily = n.GetStringValue(); } },
                { "chargeEnergyTotal", n => { ChargeEnergyTotal = n.GetStringValue(); } },
                { "chargeRatedPower", n => { ChargeRatedPower = n.GetStringValue(); } },
                { "chargingLimitCurrent", n => { ChargingLimitCurrent = n.GetStringValue(); } },
                { "commonOutPut1", n => { CommonOutPut1 = n.GetCollectionOfObjectValues<global::DynessConnector.Client.Models.DeviceOutModel>(global::DynessConnector.Client.Models.DeviceOutModel.CreateFromDiscriminatorValue)?.AsList(); } },
                { "communicationProtocolVersion", n => { CommunicationProtocolVersion = n.GetStringValue(); } },
                { "ctStatus", n => { CtStatus = n.GetStringValue(); } },
                { "dateTime", n => { DateTime = n.GetStringValue(); } },
                { "dayElectricity", n => { DayElectricity = n.GetStringValue(); } },
                { "dayGeneration", n => { DayGeneration = n.GetStringValue(); } },
                { "deviceHardwareVersion", n => { DeviceHardwareVersion = n.GetStringValue(); } },
                { "disChargeEnergyDaily", n => { DisChargeEnergyDaily = n.GetStringValue(); } },
                { "disChargeEnergyTotal", n => { DisChargeEnergyTotal = n.GetStringValue(); } },
                { "dischargeLimitCurrent", n => { DischargeLimitCurrent = n.GetStringValue(); } },
                { "dsp1Version", n => { Dsp1Version = n.GetStringValue(); } },
                { "dsp2Version", n => { Dsp2Version = n.GetStringValue(); } },
                { "dspInnerVersion", n => { DspInnerVersion = n.GetStringValue(); } },
                { "dspSvnVersion", n => { DspSvnVersion = n.GetStringValue(); } },
                { "faultInformations", n => { FaultInformations = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "firmwareVersion", n => { FirmwareVersion = n.GetStringValue(); } },
                { "generationPower", n => { GenerationPower = n.GetStringValue(); } },
                { "gridCurrentR", n => { GridCurrentR = n.GetStringValue(); } },
                { "gridCurrentS", n => { GridCurrentS = n.GetStringValue(); } },
                { "gridCurrentT", n => { GridCurrentT = n.GetStringValue(); } },
                { "gridDischargeDepth", n => { GridDischargeDepth = n.GetStringValue(); } },
                { "gridFrequencyR", n => { GridFrequencyR = n.GetStringValue(); } },
                { "gridFrequencyS", n => { GridFrequencyS = n.GetStringValue(); } },
                { "gridFrequencyT", n => { GridFrequencyT = n.GetStringValue(); } },
                { "gridPower", n => { GridPower = n.GetStringValue(); } },
                { "gridStatus", n => { GridStatus = n.GetStringValue(); } },
                { "heatDissipationTemperature", n => { HeatDissipationTemperature = n.GetStringValue(); } },
                { "householdLoad", n => { HouseholdLoad = n.GetStringValue(); } },
                { "internalTemperature", n => { InternalTemperature = n.GetStringValue(); } },
                { "lastUpdateTime", n => { LastUpdateTime = n.GetStringValue(); } },
                { "loadPower", n => { LoadPower = n.GetStringValue(); } },
                { "manufacturer", n => { Manufacturer = n.GetStringValue(); } },
                { "maxLeadBatCapacity", n => { MaxLeadBatCapacity = n.GetStringValue(); } },
                { "meterCommunication", n => { MeterCommunication = n.GetStringValue(); } },
                { "meterStatus", n => { MeterStatus = n.GetStringValue(); } },
                { "moduleTemperature", n => { ModuleTemperature = n.GetStringValue(); } },
                { "nbusVoltage", n => { NbusVoltage = n.GetStringValue(); } },
                { "offGridDischargeDepth", n => { OffGridDischargeDepth = n.GetStringValue(); } },
                { "outPut1", n => { OutPut1 = n.GetCollectionOfObjectValues<global::DynessConnector.Client.Models.DeviceOutModel>(global::DynessConnector.Client.Models.DeviceOutModel.CreateFromDiscriminatorValue)?.AsList(); } },
                { "outputMethod", n => { OutputMethod = n.GetStringValue(); } },
                { "powerLimit", n => { PowerLimit = n.GetStringValue(); } },
                { "pv1Current", n => { Pv1Current = n.GetStringValue(); } },
                { "pv1Power", n => { Pv1Power = n.GetStringValue(); } },
                { "pv1Status", n => { Pv1Status = n.GetStringValue(); } },
                { "pv1Voltage", n => { Pv1Voltage = n.GetStringValue(); } },
                { "pv2Current", n => { Pv2Current = n.GetStringValue(); } },
                { "pv2Power", n => { Pv2Power = n.GetStringValue(); } },
                { "pv2Status", n => { Pv2Status = n.GetStringValue(); } },
                { "pv2Voltage", n => { Pv2Voltage = n.GetStringValue(); } },
                { "pv3Current", n => { Pv3Current = n.GetStringValue(); } },
                { "pv3Power", n => { Pv3Power = n.GetStringValue(); } },
                { "pv3Status", n => { Pv3Status = n.GetStringValue(); } },
                { "pv3Voltage", n => { Pv3Voltage = n.GetStringValue(); } },
                { "pv4Current", n => { Pv4Current = n.GetStringValue(); } },
                { "pv4Power", n => { Pv4Power = n.GetStringValue(); } },
                { "pv4Status", n => { Pv4Status = n.GetStringValue(); } },
                { "pv4Voltage", n => { Pv4Voltage = n.GetStringValue(); } },
                { "pvPower", n => { PvPower = n.GetStringValue(); } },
                { "ratedPower", n => { RatedPower = n.GetStringValue(); } },
                { "rcurrent", n => { Rcurrent = n.GetStringValue(); } },
                { "reactivePower", n => { ReactivePower = n.GetStringValue(); } },
                { "rgridFrequency", n => { RgridFrequency = n.GetStringValue(); } },
                { "rpower", n => { Rpower = n.GetStringValue(); } },
                { "rspareCurrent", n => { RspareCurrent = n.GetStringValue(); } },
                { "rspareGridFrequency", n => { RspareGridFrequency = n.GetStringValue(); } },
                { "rsparePower", n => { RsparePower = n.GetStringValue(); } },
                { "rspareVoltage", n => { RspareVoltage = n.GetStringValue(); } },
                { "runModel", n => { RunModel = n.GetStringValue(); } },
                { "rvoltage", n => { Rvoltage = n.GetStringValue(); } },
                { "safetyCountry", n => { SafetyCountry = n.GetStringValue(); } },
                { "sellEnergy", n => { SellEnergy = n.GetStringValue(); } },
                { "sn", n => { Sn = n.GetStringValue(); } },
                { "sparePower", n => { SparePower = n.GetStringValue(); } },
                { "standByOutPut1", n => { StandByOutPut1 = n.GetCollectionOfObjectValues<global::DynessConnector.Client.Models.DeviceOutModel>(global::DynessConnector.Client.Models.DeviceOutModel.CreateFromDiscriminatorValue)?.AsList(); } },
                { "totalBuyEnergy", n => { TotalBuyEnergy = n.GetStringValue(); } },
                { "totalElectricity", n => { TotalElectricity = n.GetStringValue(); } },
                { "totalGeneration", n => { TotalGeneration = n.GetStringValue(); } },
                { "totalSellEnergy", n => { TotalSellEnergy = n.GetStringValue(); } },
                { "version", n => { Version = n.GetStringValue(); } },
                { "workStatus", n => { WorkStatus = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("acCouplingPowerR", AcCouplingPowerR);
            writer.WriteStringValue("activePower", ActivePower);
            writer.WriteStringValue("alarmInformation", AlarmInformation);
            writer.WriteStringValue("apparentPower", ApparentPower);
            writer.WriteStringValue("armInnerVersion", ArmInnerVersion);
            writer.WriteStringValue("armSvnVersion", ArmSvnVersion);
            writer.WriteStringValue("armVersion", ArmVersion);
            writer.WriteStringValue("backupLoad", BackupLoad);
            writer.WriteStringValue("batteryCapacity", BatteryCapacity);
            writer.WriteStringValue("batteryCount", BatteryCount);
            writer.WriteStringValue("batteryCurrent", BatteryCurrent);
            writer.WriteStringValue("batteryPower", BatteryPower);
            writer.WriteStringValue("batterySoc", BatterySoc);
            writer.WriteStringValue("batterySoh", BatterySoh);
            writer.WriteStringValue("batteryStatus", BatteryStatus);
            writer.WriteStringValue("batteryTemperature", BatteryTemperature);
            writer.WriteStringValue("batteryVoltage", BatteryVoltage);
            writer.WriteStringValue("bmsCommunication", BmsCommunication);
            writer.WriteStringValue("bmsCommunicationStatus", BmsCommunicationStatus);
            writer.WriteStringValue("boxCommunication", BoxCommunication);
            writer.WriteStringValue("boxSvnVersion", BoxSvnVersion);
            writer.WriteStringValue("boxVersion", BoxVersion);
            writer.WriteStringValue("busVoltage", BusVoltage);
            writer.WriteStringValue("buyEnergy", BuyEnergy);
            writer.WriteStringValue("chargeEnergyDaily", ChargeEnergyDaily);
            writer.WriteStringValue("chargeEnergyTotal", ChargeEnergyTotal);
            writer.WriteStringValue("chargeRatedPower", ChargeRatedPower);
            writer.WriteStringValue("chargingLimitCurrent", ChargingLimitCurrent);
            writer.WriteCollectionOfObjectValues<global::DynessConnector.Client.Models.DeviceOutModel>("commonOutPut1", CommonOutPut1);
            writer.WriteStringValue("communicationProtocolVersion", CommunicationProtocolVersion);
            writer.WriteStringValue("ctStatus", CtStatus);
            writer.WriteStringValue("dateTime", DateTime);
            writer.WriteStringValue("dayElectricity", DayElectricity);
            writer.WriteStringValue("dayGeneration", DayGeneration);
            writer.WriteStringValue("deviceHardwareVersion", DeviceHardwareVersion);
            writer.WriteStringValue("disChargeEnergyDaily", DisChargeEnergyDaily);
            writer.WriteStringValue("disChargeEnergyTotal", DisChargeEnergyTotal);
            writer.WriteStringValue("dischargeLimitCurrent", DischargeLimitCurrent);
            writer.WriteStringValue("dsp1Version", Dsp1Version);
            writer.WriteStringValue("dsp2Version", Dsp2Version);
            writer.WriteStringValue("dspInnerVersion", DspInnerVersion);
            writer.WriteStringValue("dspSvnVersion", DspSvnVersion);
            writer.WriteCollectionOfPrimitiveValues<string>("faultInformations", FaultInformations);
            writer.WriteStringValue("firmwareVersion", FirmwareVersion);
            writer.WriteStringValue("generationPower", GenerationPower);
            writer.WriteStringValue("gridCurrentR", GridCurrentR);
            writer.WriteStringValue("gridCurrentS", GridCurrentS);
            writer.WriteStringValue("gridCurrentT", GridCurrentT);
            writer.WriteStringValue("gridDischargeDepth", GridDischargeDepth);
            writer.WriteStringValue("gridFrequencyR", GridFrequencyR);
            writer.WriteStringValue("gridFrequencyS", GridFrequencyS);
            writer.WriteStringValue("gridFrequencyT", GridFrequencyT);
            writer.WriteStringValue("gridPower", GridPower);
            writer.WriteStringValue("gridStatus", GridStatus);
            writer.WriteStringValue("heatDissipationTemperature", HeatDissipationTemperature);
            writer.WriteStringValue("householdLoad", HouseholdLoad);
            writer.WriteStringValue("internalTemperature", InternalTemperature);
            writer.WriteStringValue("lastUpdateTime", LastUpdateTime);
            writer.WriteStringValue("loadPower", LoadPower);
            writer.WriteStringValue("manufacturer", Manufacturer);
            writer.WriteStringValue("maxLeadBatCapacity", MaxLeadBatCapacity);
            writer.WriteStringValue("meterCommunication", MeterCommunication);
            writer.WriteStringValue("meterStatus", MeterStatus);
            writer.WriteStringValue("moduleTemperature", ModuleTemperature);
            writer.WriteStringValue("nbusVoltage", NbusVoltage);
            writer.WriteStringValue("offGridDischargeDepth", OffGridDischargeDepth);
            writer.WriteCollectionOfObjectValues<global::DynessConnector.Client.Models.DeviceOutModel>("outPut1", OutPut1);
            writer.WriteStringValue("outputMethod", OutputMethod);
            writer.WriteStringValue("powerLimit", PowerLimit);
            writer.WriteStringValue("pv1Current", Pv1Current);
            writer.WriteStringValue("pv1Power", Pv1Power);
            writer.WriteStringValue("pv1Status", Pv1Status);
            writer.WriteStringValue("pv1Voltage", Pv1Voltage);
            writer.WriteStringValue("pv2Current", Pv2Current);
            writer.WriteStringValue("pv2Power", Pv2Power);
            writer.WriteStringValue("pv2Status", Pv2Status);
            writer.WriteStringValue("pv2Voltage", Pv2Voltage);
            writer.WriteStringValue("pv3Current", Pv3Current);
            writer.WriteStringValue("pv3Power", Pv3Power);
            writer.WriteStringValue("pv3Status", Pv3Status);
            writer.WriteStringValue("pv3Voltage", Pv3Voltage);
            writer.WriteStringValue("pv4Current", Pv4Current);
            writer.WriteStringValue("pv4Power", Pv4Power);
            writer.WriteStringValue("pv4Status", Pv4Status);
            writer.WriteStringValue("pv4Voltage", Pv4Voltage);
            writer.WriteStringValue("pvPower", PvPower);
            writer.WriteStringValue("ratedPower", RatedPower);
            writer.WriteStringValue("rcurrent", Rcurrent);
            writer.WriteStringValue("reactivePower", ReactivePower);
            writer.WriteStringValue("rgridFrequency", RgridFrequency);
            writer.WriteStringValue("rpower", Rpower);
            writer.WriteStringValue("rspareCurrent", RspareCurrent);
            writer.WriteStringValue("rspareGridFrequency", RspareGridFrequency);
            writer.WriteStringValue("rsparePower", RsparePower);
            writer.WriteStringValue("rspareVoltage", RspareVoltage);
            writer.WriteStringValue("runModel", RunModel);
            writer.WriteStringValue("rvoltage", Rvoltage);
            writer.WriteStringValue("safetyCountry", SafetyCountry);
            writer.WriteStringValue("sellEnergy", SellEnergy);
            writer.WriteStringValue("sn", Sn);
            writer.WriteStringValue("sparePower", SparePower);
            writer.WriteCollectionOfObjectValues<global::DynessConnector.Client.Models.DeviceOutModel>("standByOutPut1", StandByOutPut1);
            writer.WriteStringValue("totalBuyEnergy", TotalBuyEnergy);
            writer.WriteStringValue("totalElectricity", TotalElectricity);
            writer.WriteStringValue("totalGeneration", TotalGeneration);
            writer.WriteStringValue("totalSellEnergy", TotalSellEnergy);
            writer.WriteStringValue("version", Version);
            writer.WriteStringValue("workStatus", WorkStatus);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
