// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DynessConnector.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ResponseOpenApiCommerceEmsLoadDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Critical load phase A power factor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadAPowerFactor { get; set; }
#nullable restore
#else
        public string CriticalLoadAPowerFactor { get; set; }
#endif
        /// <summary>Critical load phase B power factor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadBPowerFactor { get; set; }
#nullable restore
#else
        public string CriticalLoadBPowerFactor { get; set; }
#endif
        /// <summary>Critical load phase C power factor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadCPowerFactor { get; set; }
#nullable restore
#else
        public string CriticalLoadCPowerFactor { get; set; }
#endif
        /// <summary>Critical load frequency</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadFrequency { get; set; }
#nullable restore
#else
        public string CriticalLoadFrequency { get; set; }
#endif
        /// <summary>Critical load frequency unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadFrequencyUnit { get; set; }
#nullable restore
#else
        public string CriticalLoadFrequencyUnit { get; set; }
#endif
        /// <summary>Critical load phase A current</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadPhaseACurrent { get; set; }
#nullable restore
#else
        public string CriticalLoadPhaseACurrent { get; set; }
#endif
        /// <summary>Critical load phase A power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadPhaseAPower { get; set; }
#nullable restore
#else
        public string CriticalLoadPhaseAPower { get; set; }
#endif
        /// <summary>Critical load phase A power unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadPhaseAPowerUnit { get; set; }
#nullable restore
#else
        public string CriticalLoadPhaseAPowerUnit { get; set; }
#endif
        /// <summary>Critical load phase A voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadPhaseAVoltage { get; set; }
#nullable restore
#else
        public string CriticalLoadPhaseAVoltage { get; set; }
#endif
        /// <summary>Critical load phase B current</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadPhaseBCurrent { get; set; }
#nullable restore
#else
        public string CriticalLoadPhaseBCurrent { get; set; }
#endif
        /// <summary>Critical load phase B power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadPhaseBPower { get; set; }
#nullable restore
#else
        public string CriticalLoadPhaseBPower { get; set; }
#endif
        /// <summary>Critical load phase B power unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadPhaseBPowerUnit { get; set; }
#nullable restore
#else
        public string CriticalLoadPhaseBPowerUnit { get; set; }
#endif
        /// <summary>Critical load phase B voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadPhaseBVoltage { get; set; }
#nullable restore
#else
        public string CriticalLoadPhaseBVoltage { get; set; }
#endif
        /// <summary>Critical load phase C current</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadPhaseCCurrent { get; set; }
#nullable restore
#else
        public string CriticalLoadPhaseCCurrent { get; set; }
#endif
        /// <summary>Critical load phase C power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadPhaseCPower { get; set; }
#nullable restore
#else
        public string CriticalLoadPhaseCPower { get; set; }
#endif
        /// <summary>Critical load phase C power unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadPhaseCPowerUnit { get; set; }
#nullable restore
#else
        public string CriticalLoadPhaseCPowerUnit { get; set; }
#endif
        /// <summary>Critical load phase current unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadPhaseCurrentUnit { get; set; }
#nullable restore
#else
        public string CriticalLoadPhaseCurrentUnit { get; set; }
#endif
        /// <summary>Critical load phase C voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadPhaseCVoltage { get; set; }
#nullable restore
#else
        public string CriticalLoadPhaseCVoltage { get; set; }
#endif
        /// <summary>Critical load phase power unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadPhasePowerUnit { get; set; }
#nullable restore
#else
        public string CriticalLoadPhasePowerUnit { get; set; }
#endif
        /// <summary>Critical load phase voltage unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadPhaseVoltageUnit { get; set; }
#nullable restore
#else
        public string CriticalLoadPhaseVoltageUnit { get; set; }
#endif
        /// <summary>Critical load total power factor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadPowerFactor { get; set; }
#nullable restore
#else
        public string CriticalLoadPowerFactor { get; set; }
#endif
        /// <summary>Critical load total power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadTotalPower { get; set; }
#nullable restore
#else
        public string CriticalLoadTotalPower { get; set; }
#endif
        /// <summary>Critical load total power unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CriticalLoadTotalPowerUnit { get; set; }
#nullable restore
#else
        public string CriticalLoadTotalPowerUnit { get; set; }
#endif
        /// <summary>General load phase A power factor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadAPowerFactor { get; set; }
#nullable restore
#else
        public string GeneralLoadAPowerFactor { get; set; }
#endif
        /// <summary>General load phase B power factor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadBPowerFactor { get; set; }
#nullable restore
#else
        public string GeneralLoadBPowerFactor { get; set; }
#endif
        /// <summary>General load phase C power factor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadCPowerFactor { get; set; }
#nullable restore
#else
        public string GeneralLoadCPowerFactor { get; set; }
#endif
        /// <summary>General load frequency</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadFrequency { get; set; }
#nullable restore
#else
        public string GeneralLoadFrequency { get; set; }
#endif
        /// <summary>General load frequency unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadFrequencyUnit { get; set; }
#nullable restore
#else
        public string GeneralLoadFrequencyUnit { get; set; }
#endif
        /// <summary>General load phase A current</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadPhaseACurrent { get; set; }
#nullable restore
#else
        public string GeneralLoadPhaseACurrent { get; set; }
#endif
        /// <summary>General load phase A power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadPhaseAPower { get; set; }
#nullable restore
#else
        public string GeneralLoadPhaseAPower { get; set; }
#endif
        /// <summary>General load phase A power unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadPhaseAPowerUnit { get; set; }
#nullable restore
#else
        public string GeneralLoadPhaseAPowerUnit { get; set; }
#endif
        /// <summary>General load phase A voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadPhaseAVoltage { get; set; }
#nullable restore
#else
        public string GeneralLoadPhaseAVoltage { get; set; }
#endif
        /// <summary>General load phase B current</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadPhaseBCurrent { get; set; }
#nullable restore
#else
        public string GeneralLoadPhaseBCurrent { get; set; }
#endif
        /// <summary>General load phase B power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadPhaseBPower { get; set; }
#nullable restore
#else
        public string GeneralLoadPhaseBPower { get; set; }
#endif
        /// <summary>General load phase B power unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadPhaseBPowerUnit { get; set; }
#nullable restore
#else
        public string GeneralLoadPhaseBPowerUnit { get; set; }
#endif
        /// <summary>General load phase B voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadPhaseBVoltage { get; set; }
#nullable restore
#else
        public string GeneralLoadPhaseBVoltage { get; set; }
#endif
        /// <summary>General load phase C current</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadPhaseCCurrent { get; set; }
#nullable restore
#else
        public string GeneralLoadPhaseCCurrent { get; set; }
#endif
        /// <summary>General load phase C power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadPhaseCPower { get; set; }
#nullable restore
#else
        public string GeneralLoadPhaseCPower { get; set; }
#endif
        /// <summary>General load phase C power unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadPhaseCPowerUnit { get; set; }
#nullable restore
#else
        public string GeneralLoadPhaseCPowerUnit { get; set; }
#endif
        /// <summary>General load phase current unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadPhaseCurrentUnit { get; set; }
#nullable restore
#else
        public string GeneralLoadPhaseCurrentUnit { get; set; }
#endif
        /// <summary>General load phase C voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadPhaseCVoltage { get; set; }
#nullable restore
#else
        public string GeneralLoadPhaseCVoltage { get; set; }
#endif
        /// <summary>General load phase power unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadPhasePowerUnit { get; set; }
#nullable restore
#else
        public string GeneralLoadPhasePowerUnit { get; set; }
#endif
        /// <summary>General load phase voltage unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadPhaseVoltageUnit { get; set; }
#nullable restore
#else
        public string GeneralLoadPhaseVoltageUnit { get; set; }
#endif
        /// <summary>General load total power factor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadPowerFactor { get; set; }
#nullable restore
#else
        public string GeneralLoadPowerFactor { get; set; }
#endif
        /// <summary>General load total power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadTotalPower { get; set; }
#nullable restore
#else
        public string GeneralLoadTotalPower { get; set; }
#endif
        /// <summary>General load total power unit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralLoadTotalPowerUnit { get; set; }
#nullable restore
#else
        public string GeneralLoadTotalPowerUnit { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.Models.ResponseOpenApiCommerceEmsLoadDto"/> and sets the default values.
        /// </summary>
        public ResponseOpenApiCommerceEmsLoadDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DynessConnector.Client.Models.ResponseOpenApiCommerceEmsLoadDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DynessConnector.Client.Models.ResponseOpenApiCommerceEmsLoadDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DynessConnector.Client.Models.ResponseOpenApiCommerceEmsLoadDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "criticalLoadAPowerFactor", n => { CriticalLoadAPowerFactor = n.GetStringValue(); } },
                { "criticalLoadBPowerFactor", n => { CriticalLoadBPowerFactor = n.GetStringValue(); } },
                { "criticalLoadCPowerFactor", n => { CriticalLoadCPowerFactor = n.GetStringValue(); } },
                { "criticalLoadFrequency", n => { CriticalLoadFrequency = n.GetStringValue(); } },
                { "criticalLoadFrequencyUnit", n => { CriticalLoadFrequencyUnit = n.GetStringValue(); } },
                { "criticalLoadPhaseACurrent", n => { CriticalLoadPhaseACurrent = n.GetStringValue(); } },
                { "criticalLoadPhaseAPower", n => { CriticalLoadPhaseAPower = n.GetStringValue(); } },
                { "criticalLoadPhaseAPowerUnit", n => { CriticalLoadPhaseAPowerUnit = n.GetStringValue(); } },
                { "criticalLoadPhaseAVoltage", n => { CriticalLoadPhaseAVoltage = n.GetStringValue(); } },
                { "criticalLoadPhaseBCurrent", n => { CriticalLoadPhaseBCurrent = n.GetStringValue(); } },
                { "criticalLoadPhaseBPower", n => { CriticalLoadPhaseBPower = n.GetStringValue(); } },
                { "criticalLoadPhaseBPowerUnit", n => { CriticalLoadPhaseBPowerUnit = n.GetStringValue(); } },
                { "criticalLoadPhaseBVoltage", n => { CriticalLoadPhaseBVoltage = n.GetStringValue(); } },
                { "criticalLoadPhaseCCurrent", n => { CriticalLoadPhaseCCurrent = n.GetStringValue(); } },
                { "criticalLoadPhaseCPower", n => { CriticalLoadPhaseCPower = n.GetStringValue(); } },
                { "criticalLoadPhaseCPowerUnit", n => { CriticalLoadPhaseCPowerUnit = n.GetStringValue(); } },
                { "criticalLoadPhaseCVoltage", n => { CriticalLoadPhaseCVoltage = n.GetStringValue(); } },
                { "criticalLoadPhaseCurrentUnit", n => { CriticalLoadPhaseCurrentUnit = n.GetStringValue(); } },
                { "criticalLoadPhasePowerUnit", n => { CriticalLoadPhasePowerUnit = n.GetStringValue(); } },
                { "criticalLoadPhaseVoltageUnit", n => { CriticalLoadPhaseVoltageUnit = n.GetStringValue(); } },
                { "criticalLoadPowerFactor", n => { CriticalLoadPowerFactor = n.GetStringValue(); } },
                { "criticalLoadTotalPower", n => { CriticalLoadTotalPower = n.GetStringValue(); } },
                { "criticalLoadTotalPowerUnit", n => { CriticalLoadTotalPowerUnit = n.GetStringValue(); } },
                { "generalLoadAPowerFactor", n => { GeneralLoadAPowerFactor = n.GetStringValue(); } },
                { "generalLoadBPowerFactor", n => { GeneralLoadBPowerFactor = n.GetStringValue(); } },
                { "generalLoadCPowerFactor", n => { GeneralLoadCPowerFactor = n.GetStringValue(); } },
                { "generalLoadFrequency", n => { GeneralLoadFrequency = n.GetStringValue(); } },
                { "generalLoadFrequencyUnit", n => { GeneralLoadFrequencyUnit = n.GetStringValue(); } },
                { "generalLoadPhaseACurrent", n => { GeneralLoadPhaseACurrent = n.GetStringValue(); } },
                { "generalLoadPhaseAPower", n => { GeneralLoadPhaseAPower = n.GetStringValue(); } },
                { "generalLoadPhaseAPowerUnit", n => { GeneralLoadPhaseAPowerUnit = n.GetStringValue(); } },
                { "generalLoadPhaseAVoltage", n => { GeneralLoadPhaseAVoltage = n.GetStringValue(); } },
                { "generalLoadPhaseBCurrent", n => { GeneralLoadPhaseBCurrent = n.GetStringValue(); } },
                { "generalLoadPhaseBPower", n => { GeneralLoadPhaseBPower = n.GetStringValue(); } },
                { "generalLoadPhaseBPowerUnit", n => { GeneralLoadPhaseBPowerUnit = n.GetStringValue(); } },
                { "generalLoadPhaseBVoltage", n => { GeneralLoadPhaseBVoltage = n.GetStringValue(); } },
                { "generalLoadPhaseCCurrent", n => { GeneralLoadPhaseCCurrent = n.GetStringValue(); } },
                { "generalLoadPhaseCPower", n => { GeneralLoadPhaseCPower = n.GetStringValue(); } },
                { "generalLoadPhaseCPowerUnit", n => { GeneralLoadPhaseCPowerUnit = n.GetStringValue(); } },
                { "generalLoadPhaseCVoltage", n => { GeneralLoadPhaseCVoltage = n.GetStringValue(); } },
                { "generalLoadPhaseCurrentUnit", n => { GeneralLoadPhaseCurrentUnit = n.GetStringValue(); } },
                { "generalLoadPhasePowerUnit", n => { GeneralLoadPhasePowerUnit = n.GetStringValue(); } },
                { "generalLoadPhaseVoltageUnit", n => { GeneralLoadPhaseVoltageUnit = n.GetStringValue(); } },
                { "generalLoadPowerFactor", n => { GeneralLoadPowerFactor = n.GetStringValue(); } },
                { "generalLoadTotalPower", n => { GeneralLoadTotalPower = n.GetStringValue(); } },
                { "generalLoadTotalPowerUnit", n => { GeneralLoadTotalPowerUnit = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("criticalLoadAPowerFactor", CriticalLoadAPowerFactor);
            writer.WriteStringValue("criticalLoadBPowerFactor", CriticalLoadBPowerFactor);
            writer.WriteStringValue("criticalLoadCPowerFactor", CriticalLoadCPowerFactor);
            writer.WriteStringValue("criticalLoadFrequency", CriticalLoadFrequency);
            writer.WriteStringValue("criticalLoadFrequencyUnit", CriticalLoadFrequencyUnit);
            writer.WriteStringValue("criticalLoadPhaseACurrent", CriticalLoadPhaseACurrent);
            writer.WriteStringValue("criticalLoadPhaseAPower", CriticalLoadPhaseAPower);
            writer.WriteStringValue("criticalLoadPhaseAPowerUnit", CriticalLoadPhaseAPowerUnit);
            writer.WriteStringValue("criticalLoadPhaseAVoltage", CriticalLoadPhaseAVoltage);
            writer.WriteStringValue("criticalLoadPhaseBCurrent", CriticalLoadPhaseBCurrent);
            writer.WriteStringValue("criticalLoadPhaseBPower", CriticalLoadPhaseBPower);
            writer.WriteStringValue("criticalLoadPhaseBPowerUnit", CriticalLoadPhaseBPowerUnit);
            writer.WriteStringValue("criticalLoadPhaseBVoltage", CriticalLoadPhaseBVoltage);
            writer.WriteStringValue("criticalLoadPhaseCCurrent", CriticalLoadPhaseCCurrent);
            writer.WriteStringValue("criticalLoadPhaseCPower", CriticalLoadPhaseCPower);
            writer.WriteStringValue("criticalLoadPhaseCPowerUnit", CriticalLoadPhaseCPowerUnit);
            writer.WriteStringValue("criticalLoadPhaseCurrentUnit", CriticalLoadPhaseCurrentUnit);
            writer.WriteStringValue("criticalLoadPhaseCVoltage", CriticalLoadPhaseCVoltage);
            writer.WriteStringValue("criticalLoadPhasePowerUnit", CriticalLoadPhasePowerUnit);
            writer.WriteStringValue("criticalLoadPhaseVoltageUnit", CriticalLoadPhaseVoltageUnit);
            writer.WriteStringValue("criticalLoadPowerFactor", CriticalLoadPowerFactor);
            writer.WriteStringValue("criticalLoadTotalPower", CriticalLoadTotalPower);
            writer.WriteStringValue("criticalLoadTotalPowerUnit", CriticalLoadTotalPowerUnit);
            writer.WriteStringValue("generalLoadAPowerFactor", GeneralLoadAPowerFactor);
            writer.WriteStringValue("generalLoadBPowerFactor", GeneralLoadBPowerFactor);
            writer.WriteStringValue("generalLoadCPowerFactor", GeneralLoadCPowerFactor);
            writer.WriteStringValue("generalLoadFrequency", GeneralLoadFrequency);
            writer.WriteStringValue("generalLoadFrequencyUnit", GeneralLoadFrequencyUnit);
            writer.WriteStringValue("generalLoadPhaseACurrent", GeneralLoadPhaseACurrent);
            writer.WriteStringValue("generalLoadPhaseAPower", GeneralLoadPhaseAPower);
            writer.WriteStringValue("generalLoadPhaseAPowerUnit", GeneralLoadPhaseAPowerUnit);
            writer.WriteStringValue("generalLoadPhaseAVoltage", GeneralLoadPhaseAVoltage);
            writer.WriteStringValue("generalLoadPhaseBCurrent", GeneralLoadPhaseBCurrent);
            writer.WriteStringValue("generalLoadPhaseBPower", GeneralLoadPhaseBPower);
            writer.WriteStringValue("generalLoadPhaseBPowerUnit", GeneralLoadPhaseBPowerUnit);
            writer.WriteStringValue("generalLoadPhaseBVoltage", GeneralLoadPhaseBVoltage);
            writer.WriteStringValue("generalLoadPhaseCCurrent", GeneralLoadPhaseCCurrent);
            writer.WriteStringValue("generalLoadPhaseCPower", GeneralLoadPhaseCPower);
            writer.WriteStringValue("generalLoadPhaseCPowerUnit", GeneralLoadPhaseCPowerUnit);
            writer.WriteStringValue("generalLoadPhaseCurrentUnit", GeneralLoadPhaseCurrentUnit);
            writer.WriteStringValue("generalLoadPhaseCVoltage", GeneralLoadPhaseCVoltage);
            writer.WriteStringValue("generalLoadPhasePowerUnit", GeneralLoadPhasePowerUnit);
            writer.WriteStringValue("generalLoadPhaseVoltageUnit", GeneralLoadPhaseVoltageUnit);
            writer.WriteStringValue("generalLoadPowerFactor", GeneralLoadPowerFactor);
            writer.WriteStringValue("generalLoadTotalPower", GeneralLoadTotalPower);
            writer.WriteStringValue("generalLoadTotalPowerUnit", GeneralLoadTotalPowerUnit);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
