// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DynessConnector.Client.Models
{
    /// <summary>
    /// Base device data (inherited by subclasses)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResponseAioBaseDeviceDataDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Active power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActivePower { get; set; }
#nullable restore
#else
        public string ActivePower { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Apparent power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApparentPower { get; set; }
#nullable restore
#else
        public string ApparentPower { get; set; }
#endif
        /// <summary>Battery current</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryCurrent { get; set; }
#nullable restore
#else
        public string BatteryCurrent { get; set; }
#endif
        /// <summary>Battery power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryPower { get; set; }
#nullable restore
#else
        public string BatteryPower { get; set; }
#endif
        /// <summary>Battery SOC</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatterySoc { get; set; }
#nullable restore
#else
        public string BatterySoc { get; set; }
#endif
        /// <summary>Battery SOH</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatterySoh { get; set; }
#nullable restore
#else
        public string BatterySoh { get; set; }
#endif
        /// <summary>Battery status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryStatus { get; set; }
#nullable restore
#else
        public string BatteryStatus { get; set; }
#endif
        /// <summary>Battery temperature</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryTemperature { get; set; }
#nullable restore
#else
        public string BatteryTemperature { get; set; }
#endif
        /// <summary>Battery voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryVoltage { get; set; }
#nullable restore
#else
        public string BatteryVoltage { get; set; }
#endif
        /// <summary>BMS communication status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BmsCommunicationStatus { get; set; }
#nullable restore
#else
        public string BmsCommunicationStatus { get; set; }
#endif
        /// <summary>Bus Voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusVoltage { get; set; }
#nullable restore
#else
        public string BusVoltage { get; set; }
#endif
        /// <summary>Buy electricity on the same day</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BuyEnergy { get; set; }
#nullable restore
#else
        public string BuyEnergy { get; set; }
#endif
        /// <summary>Charging current limiting</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChargingLimitCurrent { get; set; }
#nullable restore
#else
        public string ChargingLimitCurrent { get; set; }
#endif
        /// <summary>CT status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CtStatus { get; set; }
#nullable restore
#else
        public string CtStatus { get; set; }
#endif
        /// <summary>date time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateTime { get; set; }
#nullable restore
#else
        public string DateTime { get; set; }
#endif
        /// <summary>Daily electricity consumption</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DayElectricity { get; set; }
#nullable restore
#else
        public string DayElectricity { get; set; }
#endif
        /// <summary>Daily power generation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DayGeneration { get; set; }
#nullable restore
#else
        public string DayGeneration { get; set; }
#endif
        /// <summary>Device firmware version number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceHardwareVersion { get; set; }
#nullable restore
#else
        public string DeviceHardwareVersion { get; set; }
#endif
        /// <summary>Discharge current limiting</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DischargeLimitCurrent { get; set; }
#nullable restore
#else
        public string DischargeLimitCurrent { get; set; }
#endif
        /// <summary>DSPS software version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Dsp1Version { get; set; }
#nullable restore
#else
        public string Dsp1Version { get; set; }
#endif
        /// <summary>DSP2 version number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Dsp2Version { get; set; }
#nullable restore
#else
        public string Dsp2Version { get; set; }
#endif
        /// <summary>Internal firmware version of DSP</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DspInnerVersion { get; set; }
#nullable restore
#else
        public string DspInnerVersion { get; set; }
#endif
        /// <summary>DSP Boot version number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DspSvnVersion { get; set; }
#nullable restore
#else
        public string DspSvnVersion { get; set; }
#endif
        /// <summary>Power generation capacity</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GenerationPower { get; set; }
#nullable restore
#else
        public string GenerationPower { get; set; }
#endif
        /// <summary>Grid-connected discharge depth</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GridDischargeDepth { get; set; }
#nullable restore
#else
        public string GridDischargeDepth { get; set; }
#endif
        /// <summary>power grid status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GridStatus { get; set; }
#nullable restore
#else
        public string GridStatus { get; set; }
#endif
        /// <summary>Heat dissipation temperature</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HeatDissipationTemperature { get; set; }
#nullable restore
#else
        public string HeatDissipationTemperature { get; set; }
#endif
        /// <summary>Internal temperature</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InternalTemperature { get; set; }
#nullable restore
#else
        public string InternalTemperature { get; set; }
#endif
        /// <summary>Total load power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LoadPower { get; set; }
#nullable restore
#else
        public string LoadPower { get; set; }
#endif
        /// <summary>Electricity meter communication</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MeterCommunication { get; set; }
#nullable restore
#else
        public string MeterCommunication { get; set; }
#endif
        /// <summary>Electricity meter status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MeterStatus { get; set; }
#nullable restore
#else
        public string MeterStatus { get; set; }
#endif
        /// <summary>Module temperature</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModuleTemperature { get; set; }
#nullable restore
#else
        public string ModuleTemperature { get; set; }
#endif
        /// <summary>NBus Voltage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NbusVoltage { get; set; }
#nullable restore
#else
        public string NbusVoltage { get; set; }
#endif
        /// <summary>Off-grid discharge depth</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OffGridDischargeDepth { get; set; }
#nullable restore
#else
        public string OffGridDischargeDepth { get; set; }
#endif
        /// <summary>Output mode: 0: Single-phase 1: Three-phase four-wire system 2: Three-phase single-wire system 3: Two-phase three-wire system</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OutputMethod { get; set; }
#nullable restore
#else
        public string OutputMethod { get; set; }
#endif
        /// <summary>Grid-connected power limit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PowerLimit { get; set; }
#nullable restore
#else
        public string PowerLimit { get; set; }
#endif
        /// <summary>Reactive power</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReactivePower { get; set; }
#nullable restore
#else
        public string ReactivePower { get; set; }
#endif
        /// <summary>Operating mode</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RunModel { get; set; }
#nullable restore
#else
        public string RunModel { get; set; }
#endif
        /// <summary>Countries with safety regulations</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SafetyCountry { get; set; }
#nullable restore
#else
        public string SafetyCountry { get; set; }
#endif
        /// <summary>Sell electricity on the same day</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SellEnergy { get; set; }
#nullable restore
#else
        public string SellEnergy { get; set; }
#endif
        /// <summary>SN</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sn { get; set; }
#nullable restore
#else
        public string Sn { get; set; }
#endif
        /// <summary>Backup power supply</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SparePower { get; set; }
#nullable restore
#else
        public string SparePower { get; set; }
#endif
        /// <summary>Cumulative purchased electricity</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalBuyEnergy { get; set; }
#nullable restore
#else
        public string TotalBuyEnergy { get; set; }
#endif
        /// <summary>Total electricity consumption</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalElectricity { get; set; }
#nullable restore
#else
        public string TotalElectricity { get; set; }
#endif
        /// <summary>Cumulative power generation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalGeneration { get; set; }
#nullable restore
#else
        public string TotalGeneration { get; set; }
#endif
        /// <summary>Cumulative electricity sales</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalSellEnergy { get; set; }
#nullable restore
#else
        public string TotalSellEnergy { get; set; }
#endif
        /// <summary>Working status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkStatus { get; set; }
#nullable restore
#else
        public string WorkStatus { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.Models.ResponseAioBaseDeviceDataDto"/> and sets the default values.
        /// </summary>
        public ResponseAioBaseDeviceDataDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DynessConnector.Client.Models.ResponseAioBaseDeviceDataDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DynessConnector.Client.Models.ResponseAioBaseDeviceDataDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DynessConnector.Client.Models.ResponseAioBaseDeviceDataDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activePower", n => { ActivePower = n.GetStringValue(); } },
                { "apparentPower", n => { ApparentPower = n.GetStringValue(); } },
                { "batteryCurrent", n => { BatteryCurrent = n.GetStringValue(); } },
                { "batteryPower", n => { BatteryPower = n.GetStringValue(); } },
                { "batterySoc", n => { BatterySoc = n.GetStringValue(); } },
                { "batterySoh", n => { BatterySoh = n.GetStringValue(); } },
                { "batteryStatus", n => { BatteryStatus = n.GetStringValue(); } },
                { "batteryTemperature", n => { BatteryTemperature = n.GetStringValue(); } },
                { "batteryVoltage", n => { BatteryVoltage = n.GetStringValue(); } },
                { "bmsCommunicationStatus", n => { BmsCommunicationStatus = n.GetStringValue(); } },
                { "busVoltage", n => { BusVoltage = n.GetStringValue(); } },
                { "buyEnergy", n => { BuyEnergy = n.GetStringValue(); } },
                { "chargingLimitCurrent", n => { ChargingLimitCurrent = n.GetStringValue(); } },
                { "ctStatus", n => { CtStatus = n.GetStringValue(); } },
                { "dateTime", n => { DateTime = n.GetStringValue(); } },
                { "dayElectricity", n => { DayElectricity = n.GetStringValue(); } },
                { "dayGeneration", n => { DayGeneration = n.GetStringValue(); } },
                { "deviceHardwareVersion", n => { DeviceHardwareVersion = n.GetStringValue(); } },
                { "dischargeLimitCurrent", n => { DischargeLimitCurrent = n.GetStringValue(); } },
                { "dsp1Version", n => { Dsp1Version = n.GetStringValue(); } },
                { "dsp2Version", n => { Dsp2Version = n.GetStringValue(); } },
                { "dspInnerVersion", n => { DspInnerVersion = n.GetStringValue(); } },
                { "dspSvnVersion", n => { DspSvnVersion = n.GetStringValue(); } },
                { "generationPower", n => { GenerationPower = n.GetStringValue(); } },
                { "gridDischargeDepth", n => { GridDischargeDepth = n.GetStringValue(); } },
                { "gridStatus", n => { GridStatus = n.GetStringValue(); } },
                { "heatDissipationTemperature", n => { HeatDissipationTemperature = n.GetStringValue(); } },
                { "internalTemperature", n => { InternalTemperature = n.GetStringValue(); } },
                { "loadPower", n => { LoadPower = n.GetStringValue(); } },
                { "meterCommunication", n => { MeterCommunication = n.GetStringValue(); } },
                { "meterStatus", n => { MeterStatus = n.GetStringValue(); } },
                { "moduleTemperature", n => { ModuleTemperature = n.GetStringValue(); } },
                { "nbusVoltage", n => { NbusVoltage = n.GetStringValue(); } },
                { "offGridDischargeDepth", n => { OffGridDischargeDepth = n.GetStringValue(); } },
                { "outputMethod", n => { OutputMethod = n.GetStringValue(); } },
                { "powerLimit", n => { PowerLimit = n.GetStringValue(); } },
                { "reactivePower", n => { ReactivePower = n.GetStringValue(); } },
                { "runModel", n => { RunModel = n.GetStringValue(); } },
                { "safetyCountry", n => { SafetyCountry = n.GetStringValue(); } },
                { "sellEnergy", n => { SellEnergy = n.GetStringValue(); } },
                { "sn", n => { Sn = n.GetStringValue(); } },
                { "sparePower", n => { SparePower = n.GetStringValue(); } },
                { "totalBuyEnergy", n => { TotalBuyEnergy = n.GetStringValue(); } },
                { "totalElectricity", n => { TotalElectricity = n.GetStringValue(); } },
                { "totalGeneration", n => { TotalGeneration = n.GetStringValue(); } },
                { "totalSellEnergy", n => { TotalSellEnergy = n.GetStringValue(); } },
                { "workStatus", n => { WorkStatus = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("activePower", ActivePower);
            writer.WriteStringValue("apparentPower", ApparentPower);
            writer.WriteStringValue("batteryCurrent", BatteryCurrent);
            writer.WriteStringValue("batteryPower", BatteryPower);
            writer.WriteStringValue("batterySoc", BatterySoc);
            writer.WriteStringValue("batterySoh", BatterySoh);
            writer.WriteStringValue("batteryStatus", BatteryStatus);
            writer.WriteStringValue("batteryTemperature", BatteryTemperature);
            writer.WriteStringValue("batteryVoltage", BatteryVoltage);
            writer.WriteStringValue("bmsCommunicationStatus", BmsCommunicationStatus);
            writer.WriteStringValue("busVoltage", BusVoltage);
            writer.WriteStringValue("buyEnergy", BuyEnergy);
            writer.WriteStringValue("chargingLimitCurrent", ChargingLimitCurrent);
            writer.WriteStringValue("ctStatus", CtStatus);
            writer.WriteStringValue("dateTime", DateTime);
            writer.WriteStringValue("dayElectricity", DayElectricity);
            writer.WriteStringValue("dayGeneration", DayGeneration);
            writer.WriteStringValue("deviceHardwareVersion", DeviceHardwareVersion);
            writer.WriteStringValue("dischargeLimitCurrent", DischargeLimitCurrent);
            writer.WriteStringValue("dsp1Version", Dsp1Version);
            writer.WriteStringValue("dsp2Version", Dsp2Version);
            writer.WriteStringValue("dspInnerVersion", DspInnerVersion);
            writer.WriteStringValue("dspSvnVersion", DspSvnVersion);
            writer.WriteStringValue("generationPower", GenerationPower);
            writer.WriteStringValue("gridDischargeDepth", GridDischargeDepth);
            writer.WriteStringValue("gridStatus", GridStatus);
            writer.WriteStringValue("heatDissipationTemperature", HeatDissipationTemperature);
            writer.WriteStringValue("internalTemperature", InternalTemperature);
            writer.WriteStringValue("loadPower", LoadPower);
            writer.WriteStringValue("meterCommunication", MeterCommunication);
            writer.WriteStringValue("meterStatus", MeterStatus);
            writer.WriteStringValue("moduleTemperature", ModuleTemperature);
            writer.WriteStringValue("nbusVoltage", NbusVoltage);
            writer.WriteStringValue("offGridDischargeDepth", OffGridDischargeDepth);
            writer.WriteStringValue("outputMethod", OutputMethod);
            writer.WriteStringValue("powerLimit", PowerLimit);
            writer.WriteStringValue("reactivePower", ReactivePower);
            writer.WriteStringValue("runModel", RunModel);
            writer.WriteStringValue("safetyCountry", SafetyCountry);
            writer.WriteStringValue("sellEnergy", SellEnergy);
            writer.WriteStringValue("sn", Sn);
            writer.WriteStringValue("sparePower", SparePower);
            writer.WriteStringValue("totalBuyEnergy", TotalBuyEnergy);
            writer.WriteStringValue("totalElectricity", TotalElectricity);
            writer.WriteStringValue("totalGeneration", TotalGeneration);
            writer.WriteStringValue("totalSellEnergy", TotalSellEnergy);
            writer.WriteStringValue("workStatus", WorkStatus);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
