// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DynessConnector.Client.Models
{
    /// <summary>
    /// system energy result entity
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResponseOpenApiSystemEnergyDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>buy electricity on the same day</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BuyEnergy { get; set; }
#nullable restore
#else
        public string BuyEnergy { get; set; }
#endif
        /// <summary>daily electricity consumption</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DayElectricity { get; set; }
#nullable restore
#else
        public string DayElectricity { get; set; }
#endif
        /// <summary>daily power generation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DayGeneration { get; set; }
#nullable restore
#else
        public string DayGeneration { get; set; }
#endif
        /// <summary>sell electricity on the same day</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SellEnergy { get; set; }
#nullable restore
#else
        public string SellEnergy { get; set; }
#endif
        /// <summary>cumulative purchased electricity</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalBuyEnergy { get; set; }
#nullable restore
#else
        public string TotalBuyEnergy { get; set; }
#endif
        /// <summary>total electricity consumption</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalElectricity { get; set; }
#nullable restore
#else
        public string TotalElectricity { get; set; }
#endif
        /// <summary>cumulative power generation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalGeneration { get; set; }
#nullable restore
#else
        public string TotalGeneration { get; set; }
#endif
        /// <summary>cumulative electricity sales</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalSellEnergy { get; set; }
#nullable restore
#else
        public string TotalSellEnergy { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.Models.ResponseOpenApiSystemEnergyDto"/> and sets the default values.
        /// </summary>
        public ResponseOpenApiSystemEnergyDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DynessConnector.Client.Models.ResponseOpenApiSystemEnergyDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DynessConnector.Client.Models.ResponseOpenApiSystemEnergyDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DynessConnector.Client.Models.ResponseOpenApiSystemEnergyDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "buyEnergy", n => { BuyEnergy = n.GetStringValue(); } },
                { "dayElectricity", n => { DayElectricity = n.GetStringValue(); } },
                { "dayGeneration", n => { DayGeneration = n.GetStringValue(); } },
                { "sellEnergy", n => { SellEnergy = n.GetStringValue(); } },
                { "totalBuyEnergy", n => { TotalBuyEnergy = n.GetStringValue(); } },
                { "totalElectricity", n => { TotalElectricity = n.GetStringValue(); } },
                { "totalGeneration", n => { TotalGeneration = n.GetStringValue(); } },
                { "totalSellEnergy", n => { TotalSellEnergy = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("buyEnergy", BuyEnergy);
            writer.WriteStringValue("dayElectricity", DayElectricity);
            writer.WriteStringValue("dayGeneration", DayGeneration);
            writer.WriteStringValue("sellEnergy", SellEnergy);
            writer.WriteStringValue("totalBuyEnergy", TotalBuyEnergy);
            writer.WriteStringValue("totalElectricity", TotalElectricity);
            writer.WriteStringValue("totalGeneration", TotalGeneration);
            writer.WriteStringValue("totalSellEnergy", TotalSellEnergy);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
