// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DynessConnector.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ResponseOpenApiAlarmPageDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Battery category</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatteryCategory { get; set; }
#nullable restore
#else
        public string BatteryCategory { get; set; }
#endif
        /// <summary>Alarm start time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BeginTime { get; set; }
#nullable restore
#else
        public string BeginTime { get; set; }
#endif
        /// <summary>Clear status, 1: Cleared, 2: Uncleared</summary>
        public int? ClearStatus { get; set; }
        /// <summary>data source</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DataSource { get; set; }
#nullable restore
#else
        public string DataSource { get; set; }
#endif
        /// <summary>Device code</summary>
        public int? DeviceCode { get; set; }
        /// <summary>Device model code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceModelCode { get; set; }
#nullable restore
#else
        public string DeviceModelCode { get; set; }
#endif
        /// <summary>Device serial number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceSn { get; set; }
#nullable restore
#else
        public string DeviceSn { get; set; }
#endif
        /// <summary>Device status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceStatus { get; set; }
#nullable restore
#else
        public string DeviceStatus { get; set; }
#endif
        /// <summary>Device type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceType { get; set; }
#nullable restore
#else
        public string DeviceType { get; set; }
#endif
        /// <summary>Alarm end time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndTime { get; set; }
#nullable restore
#else
        public string EndTime { get; set; }
#endif
        /// <summary>Alarm code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventCode { get; set; }
#nullable restore
#else
        public string EventCode { get; set; }
#endif
        /// <summary>Fault content</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventContent { get; set; }
#nullable restore
#else
        public string EventContent { get; set; }
#endif
        /// <summary>Alarm level</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventGrade { get; set; }
#nullable restore
#else
        public string EventGrade { get; set; }
#endif
        /// <summary>告警类型dto</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DynessConnector.Client.Models.ResponseAlarmTypeDto? EventType { get; set; }
#nullable restore
#else
        public global::DynessConnector.Client.Models.ResponseAlarmTypeDto EventType { get; set; }
#endif
        /// <summary>Manufacturer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Factory { get; set; }
#nullable restore
#else
        public string Factory { get; set; }
#endif
        /// <summary>ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Device location</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Location { get; set; }
#nullable restore
#else
        public string Location { get; set; }
#endif
        /// <summary>Read status, 1: Read, 2: Unread</summary>
        public int? ReadStatus { get; set; }
        /// <summary>Real device serial number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RealDeviceSn { get; set; }
#nullable restore
#else
        public string RealDeviceSn { get; set; }
#endif
        /// <summary>Solution (Chinese and English)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Solution { get; set; }
#nullable restore
#else
        public string Solution { get; set; }
#endif
        /// <summary>Station address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StationAddress { get; set; }
#nullable restore
#else
        public string StationAddress { get; set; }
#endif
        /// <summary>Station ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StationId { get; set; }
#nullable restore
#else
        public string StationId { get; set; }
#endif
        /// <summary>Station name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StationName { get; set; }
#nullable restore
#else
        public string StationName { get; set; }
#endif
        /// <summary>Station type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StationType { get; set; }
#nullable restore
#else
        public string StationType { get; set; }
#endif
        /// <summary>System type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SystemType { get; set; }
#nullable restore
#else
        public string SystemType { get; set; }
#endif
        /// <summary>Time zone</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Utc { get; set; }
#nullable restore
#else
        public string Utc { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.Models.ResponseOpenApiAlarmPageDto"/> and sets the default values.
        /// </summary>
        public ResponseOpenApiAlarmPageDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DynessConnector.Client.Models.ResponseOpenApiAlarmPageDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DynessConnector.Client.Models.ResponseOpenApiAlarmPageDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DynessConnector.Client.Models.ResponseOpenApiAlarmPageDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "batteryCategory", n => { BatteryCategory = n.GetStringValue(); } },
                { "beginTime", n => { BeginTime = n.GetStringValue(); } },
                { "clearStatus", n => { ClearStatus = n.GetIntValue(); } },
                { "dataSource", n => { DataSource = n.GetStringValue(); } },
                { "deviceCode", n => { DeviceCode = n.GetIntValue(); } },
                { "deviceModelCode", n => { DeviceModelCode = n.GetStringValue(); } },
                { "deviceSn", n => { DeviceSn = n.GetStringValue(); } },
                { "deviceStatus", n => { DeviceStatus = n.GetStringValue(); } },
                { "deviceType", n => { DeviceType = n.GetStringValue(); } },
                { "endTime", n => { EndTime = n.GetStringValue(); } },
                { "eventCode", n => { EventCode = n.GetStringValue(); } },
                { "eventContent", n => { EventContent = n.GetStringValue(); } },
                { "eventGrade", n => { EventGrade = n.GetStringValue(); } },
                { "eventType", n => { EventType = n.GetObjectValue<global::DynessConnector.Client.Models.ResponseAlarmTypeDto>(global::DynessConnector.Client.Models.ResponseAlarmTypeDto.CreateFromDiscriminatorValue); } },
                { "factory", n => { Factory = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "location", n => { Location = n.GetStringValue(); } },
                { "readStatus", n => { ReadStatus = n.GetIntValue(); } },
                { "realDeviceSn", n => { RealDeviceSn = n.GetStringValue(); } },
                { "solution", n => { Solution = n.GetStringValue(); } },
                { "stationAddress", n => { StationAddress = n.GetStringValue(); } },
                { "stationId", n => { StationId = n.GetStringValue(); } },
                { "stationName", n => { StationName = n.GetStringValue(); } },
                { "stationType", n => { StationType = n.GetStringValue(); } },
                { "systemType", n => { SystemType = n.GetStringValue(); } },
                { "utc", n => { Utc = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("batteryCategory", BatteryCategory);
            writer.WriteStringValue("beginTime", BeginTime);
            writer.WriteIntValue("clearStatus", ClearStatus);
            writer.WriteStringValue("dataSource", DataSource);
            writer.WriteIntValue("deviceCode", DeviceCode);
            writer.WriteStringValue("deviceModelCode", DeviceModelCode);
            writer.WriteStringValue("deviceSn", DeviceSn);
            writer.WriteStringValue("deviceStatus", DeviceStatus);
            writer.WriteStringValue("deviceType", DeviceType);
            writer.WriteStringValue("endTime", EndTime);
            writer.WriteStringValue("eventCode", EventCode);
            writer.WriteStringValue("eventContent", EventContent);
            writer.WriteStringValue("eventGrade", EventGrade);
            writer.WriteObjectValue<global::DynessConnector.Client.Models.ResponseAlarmTypeDto>("eventType", EventType);
            writer.WriteStringValue("factory", Factory);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("location", Location);
            writer.WriteIntValue("readStatus", ReadStatus);
            writer.WriteStringValue("realDeviceSn", RealDeviceSn);
            writer.WriteStringValue("solution", Solution);
            writer.WriteStringValue("stationAddress", StationAddress);
            writer.WriteStringValue("stationId", StationId);
            writer.WriteStringValue("stationName", StationName);
            writer.WriteStringValue("stationType", StationType);
            writer.WriteStringValue("systemType", SystemType);
            writer.WriteStringValue("utc", Utc);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
