// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace EstfeedConnector.Client.Models
{
    /// <summary>
    /// API key metering point
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiKeyMeteringPoint : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Metering point commodity type</summary>
        public global::EstfeedConnector.Client.Models.ApiKeyMeteringPoint_commodityType? CommodityType { get; set; }
        /// <summary>Metering point EIC</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Eic { get; set; }
#nullable restore
#else
        public string Eic { get; set; }
#endif
        /// <summary>Periods</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::EstfeedConnector.Client.Models.PeriodDto>? Periods { get; set; }
#nullable restore
#else
        public List<global::EstfeedConnector.Client.Models.PeriodDto> Periods { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::EstfeedConnector.Client.Models.ApiKeyMeteringPoint"/> and sets the default values.
        /// </summary>
        public ApiKeyMeteringPoint()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::EstfeedConnector.Client.Models.ApiKeyMeteringPoint"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::EstfeedConnector.Client.Models.ApiKeyMeteringPoint CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::EstfeedConnector.Client.Models.ApiKeyMeteringPoint();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "commodityType", n => { CommodityType = n.GetEnumValue<global::EstfeedConnector.Client.Models.ApiKeyMeteringPoint_commodityType>(); } },
                { "eic", n => { Eic = n.GetStringValue(); } },
                { "periods", n => { Periods = n.GetCollectionOfObjectValues<global::EstfeedConnector.Client.Models.PeriodDto>(global::EstfeedConnector.Client.Models.PeriodDto.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::EstfeedConnector.Client.Models.ApiKeyMeteringPoint_commodityType>("commodityType", CommodityType);
            writer.WriteStringValue("eic", Eic);
            writer.WriteCollectionOfObjectValues<global::EstfeedConnector.Client.Models.PeriodDto>("periods", Periods);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
