// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using SolarmanV5Client.InverterSettings;
using SolarmanV5Client.Schedule;
using SolarmanV5Client.Values;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SolarmanV5Client
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SolarmanV5 : BaseRequestBuilder
    {
        /// <summary>The inverterSettings property</summary>
        public global::SolarmanV5Client.InverterSettings.InverterSettingsRequestBuilder InverterSettings
        {
            get => new global::SolarmanV5Client.InverterSettings.InverterSettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The schedule property</summary>
        public global::SolarmanV5Client.Schedule.ScheduleRequestBuilder Schedule
        {
            get => new global::SolarmanV5Client.Schedule.ScheduleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The values property</summary>
        public global::SolarmanV5Client.Values.ValuesRequestBuilder Values
        {
            get => new global::SolarmanV5Client.Values.ValuesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SolarmanV5Client.SolarmanV5"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SolarmanV5(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
