// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using MyUplinkConnector.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MyUplinkConnector.Client.V2.Systems.Item.Notifications.Active
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\systems\{systemId}\notifications\active
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class ActiveRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MyUplinkConnector.Client.V2.Systems.Item.Notifications.Active.ActiveRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActiveRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/systems/{systemId}/notifications/active{?itemsPerPage*,page*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MyUplinkConnector.Client.V2.Systems.Item.Notifications.Active.ActiveRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActiveRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/systems/{systemId}/notifications/active{?itemsPerPage*,page*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve active alarms for specified system.
        /// </summary>
        /// <returns>A <see cref="global::MyUplinkConnector.Client.Models.AlarmsPaged"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MyUplinkConnector.Client.Models.AlarmsPaged?> GetAsync(Action<RequestConfiguration<global::MyUplinkConnector.Client.V2.Systems.Item.Notifications.Active.ActiveRequestBuilder.ActiveRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MyUplinkConnector.Client.Models.AlarmsPaged> GetAsync(Action<RequestConfiguration<global::MyUplinkConnector.Client.V2.Systems.Item.Notifications.Active.ActiveRequestBuilder.ActiveRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::MyUplinkConnector.Client.Models.AlarmsPaged>(requestInfo, global::MyUplinkConnector.Client.Models.AlarmsPaged.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve active alarms for specified system.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MyUplinkConnector.Client.V2.Systems.Item.Notifications.Active.ActiveRequestBuilder.ActiveRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MyUplinkConnector.Client.V2.Systems.Item.Notifications.Active.ActiveRequestBuilder.ActiveRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MyUplinkConnector.Client.V2.Systems.Item.Notifications.Active.ActiveRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MyUplinkConnector.Client.V2.Systems.Item.Notifications.Active.ActiveRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MyUplinkConnector.Client.V2.Systems.Item.Notifications.Active.ActiveRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve active alarms for specified system.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class ActiveRequestBuilderGetQueryParameters 
        {
            /// <summary>Maximum number of results to be returned. Optional, defaults to 10.</summary>
            [QueryParameter("itemsPerPage")]
            public int? ItemsPerPage { get; set; }
            /// <summary>Page number. Optional, defaults to 1.</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class ActiveRequestBuilderGetRequestConfiguration : RequestConfiguration<global::MyUplinkConnector.Client.V2.Systems.Item.Notifications.Active.ActiveRequestBuilder.ActiveRequestBuilderGetQueryParameters>
        {
        }
    }
}
