// <auto-generated/>
#pragma warning disable CS0618
using EstfeedConnector.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace EstfeedConnector.Client.Api.Public.V1.MeteringPointEics
{
    /// <summary>
    /// Builds and executes requests for operations under \api\public\v1\metering-point-eics
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MeteringPointEicsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::EstfeedConnector.Client.Api.Public.V1.MeteringPointEics.MeteringPointEicsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MeteringPointEicsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/v1/metering-point-eics?endDateTime={endDateTime}&startDateTime={startDateTime}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EstfeedConnector.Client.Api.Public.V1.MeteringPointEics.MeteringPointEicsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MeteringPointEicsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/v1/metering-point-eics?endDateTime={endDateTime}&startDateTime={startDateTime}", rawUrl)
        {
        }
        /// <summary>
        ///   API endpoint for retrieving the list of metering point EICs connected with the given API key within the requested time interval.  This API is useful if the API key is associated with more than 10 metering points (or is dynamic and includes all  past, present and future metering points).  It allows retrieving the EIC list first, and then querying metering data in batches of up to 10 metering points  using `GET /api/public/v1/metering-data`.  The mandatory query parameters are: `startDateTime` and `endDateTime`.  The response includes all metering points associated with the API key between `startDateTime` and `endDateTime`.  Rate limit: max 1 request per 5 sec.
        /// </summary>
        /// <returns>A List&lt;global::EstfeedConnector.Client.Models.ApiKeyMeteringPoint&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::EstfeedConnector.Client.Models.ErrorResponseV2">When receiving a 400 status code</exception>
        /// <exception cref="global::EstfeedConnector.Client.Models.ErrorResponseV2">When receiving a 401 status code</exception>
        /// <exception cref="global::EstfeedConnector.Client.Models.ErrorResponseV2">When receiving a 403 status code</exception>
        /// <exception cref="global::EstfeedConnector.Client.Models.ErrorResponseV2">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::EstfeedConnector.Client.Models.ApiKeyMeteringPoint>?> GetAsync(Action<RequestConfiguration<global::EstfeedConnector.Client.Api.Public.V1.MeteringPointEics.MeteringPointEicsRequestBuilder.MeteringPointEicsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::EstfeedConnector.Client.Models.ApiKeyMeteringPoint>> GetAsync(Action<RequestConfiguration<global::EstfeedConnector.Client.Api.Public.V1.MeteringPointEics.MeteringPointEicsRequestBuilder.MeteringPointEicsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::EstfeedConnector.Client.Models.ErrorResponseV2.CreateFromDiscriminatorValue },
                { "401", global::EstfeedConnector.Client.Models.ErrorResponseV2.CreateFromDiscriminatorValue },
                { "403", global::EstfeedConnector.Client.Models.ErrorResponseV2.CreateFromDiscriminatorValue },
                { "422", global::EstfeedConnector.Client.Models.ErrorResponseV2.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::EstfeedConnector.Client.Models.ApiKeyMeteringPoint>(requestInfo, global::EstfeedConnector.Client.Models.ApiKeyMeteringPoint.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        ///   API endpoint for retrieving the list of metering point EICs connected with the given API key within the requested time interval.  This API is useful if the API key is associated with more than 10 metering points (or is dynamic and includes all  past, present and future metering points).  It allows retrieving the EIC list first, and then querying metering data in batches of up to 10 metering points  using `GET /api/public/v1/metering-data`.  The mandatory query parameters are: `startDateTime` and `endDateTime`.  The response includes all metering points associated with the API key between `startDateTime` and `endDateTime`.  Rate limit: max 1 request per 5 sec.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::EstfeedConnector.Client.Api.Public.V1.MeteringPointEics.MeteringPointEicsRequestBuilder.MeteringPointEicsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::EstfeedConnector.Client.Api.Public.V1.MeteringPointEics.MeteringPointEicsRequestBuilder.MeteringPointEicsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::EstfeedConnector.Client.Api.Public.V1.MeteringPointEics.MeteringPointEicsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::EstfeedConnector.Client.Api.Public.V1.MeteringPointEics.MeteringPointEicsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::EstfeedConnector.Client.Api.Public.V1.MeteringPointEics.MeteringPointEicsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        ///   API endpoint for retrieving the list of metering point EICs connected with the given API key within the requested time interval.  This API is useful if the API key is associated with more than 10 metering points (or is dynamic and includes all  past, present and future metering points).  It allows retrieving the EIC list first, and then querying metering data in batches of up to 10 metering points  using `GET /api/public/v1/metering-data`.  The mandatory query parameters are: `startDateTime` and `endDateTime`.  The response includes all metering points associated with the API key between `startDateTime` and `endDateTime`.  Rate limit: max 1 request per 5 sec.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MeteringPointEicsRequestBuilderGetQueryParameters 
        {
            /// <summary>End date with timeValidations:  * ISO-8601 datetime  * Has to be bigger, than &quot;startDateTime&quot;</summary>
            [QueryParameter("endDateTime")]
            public DateTimeOffset? EndDateTime { get; set; }
            /// <summary>Start date with timeValidations:  * ISO-8601 datetime  * Has to be smaller, than &quot;endDateTime&quot;</summary>
            [QueryParameter("startDateTime")]
            public DateTimeOffset? StartDateTime { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MeteringPointEicsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::EstfeedConnector.Client.Api.Public.V1.MeteringPointEics.MeteringPointEicsRequestBuilder.MeteringPointEicsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
