// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using MyUplinkConnector.Client.V2.Internal.Ssg.Systems.Item.Categories.Data;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MyUplinkConnector.Client.V2.Internal.Ssg.Systems.Item.Categories
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\internal\ssg\systems\{systemId}\categories
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class CategoriesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The data property</summary>
        public global::MyUplinkConnector.Client.V2.Internal.Ssg.Systems.Item.Categories.Data.DataRequestBuilder Data
        {
            get => new global::MyUplinkConnector.Client.V2.Internal.Ssg.Systems.Item.Categories.Data.DataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MyUplinkConnector.Client.V2.Internal.Ssg.Systems.Item.Categories.CategoriesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CategoriesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/internal/ssg/systems/{systemId}/categories", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MyUplinkConnector.Client.V2.Internal.Ssg.Systems.Item.Categories.CategoriesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CategoriesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/internal/ssg/systems/{systemId}/categories", rawUrl)
        {
        }
    }
}
