// <auto-generated/>
#pragma warning disable CS0618
using DynessConnector.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace DynessConnector.Client.V1.Group.MultiGetDischargeConfigByGroup
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\group\multiGetDischargeConfigByGroup
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MultiGetDischargeConfigByGroupRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.V1.Group.MultiGetDischargeConfigByGroup.MultiGetDischargeConfigByGroupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MultiGetDischargeConfigByGroupRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/group/multiGetDischargeConfigByGroup", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.V1.Group.MultiGetDischargeConfigByGroup.MultiGetDischargeConfigByGroupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MultiGetDischargeConfigByGroupRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/group/multiGetDischargeConfigByGroup", rawUrl)
        {
        }
        /// <summary>
        /// Only IGEN series products are supported
        /// </summary>
        /// <returns>A <see cref="global::DynessConnector.Client.Models.ResponseResultListResponseBatchChargeByGroupDto"/></returns>
        /// <param name="body">batch reading request object for charging data</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::DynessConnector.Client.Models.ResponseResultListResponseBatchChargeByGroupDto?> PostAsync(global::DynessConnector.Client.Models.RequestBatchDisChargeChargeByGroupDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::DynessConnector.Client.Models.ResponseResultListResponseBatchChargeByGroupDto> PostAsync(global::DynessConnector.Client.Models.RequestBatchDisChargeChargeByGroupDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::DynessConnector.Client.Models.ResponseResultListResponseBatchChargeByGroupDto>(requestInfo, global::DynessConnector.Client.Models.ResponseResultListResponseBatchChargeByGroupDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Only IGEN series products are supported
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">batch reading request object for charging data</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::DynessConnector.Client.Models.RequestBatchDisChargeChargeByGroupDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::DynessConnector.Client.Models.RequestBatchDisChargeChargeByGroupDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::DynessConnector.Client.V1.Group.MultiGetDischargeConfigByGroup.MultiGetDischargeConfigByGroupRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::DynessConnector.Client.V1.Group.MultiGetDischargeConfigByGroup.MultiGetDischargeConfigByGroupRequestBuilder WithUrl(string rawUrl)
        {
            return new global::DynessConnector.Client.V1.Group.MultiGetDischargeConfigByGroup.MultiGetDischargeConfigByGroupRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MultiGetDischargeConfigByGroupRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
