// <auto-generated/>
#pragma warning disable CS0618
using DynessConnector.Client.V1.Station.Info;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DynessConnector.Client.V1.Station
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\station
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The info property</summary>
        public global::DynessConnector.Client.V1.Station.Info.InfoRequestBuilder Info
        {
            get => new global::DynessConnector.Client.V1.Station.Info.InfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.V1.Station.StationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/station", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.V1.Station.StationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/station", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
