// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MyUplinkConnector.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public partial class DeviceFirmwareInfoResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The currentFwVersion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrentFwVersion { get; set; }
#nullable restore
#else
        public string CurrentFwVersion { get; set; }
#endif
        /// <summary>The desiredFwVersion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DesiredFwVersion { get; set; }
#nullable restore
#else
        public string DesiredFwVersion { get; set; }
#endif
        /// <summary>The deviceId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeviceId { get; set; }
#nullable restore
#else
        public string DeviceId { get; set; }
#endif
        /// <summary>The firmwareId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirmwareId { get; set; }
#nullable restore
#else
        public string FirmwareId { get; set; }
#endif
        /// <summary>The pendingFwVersion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PendingFwVersion { get; set; }
#nullable restore
#else
        public string PendingFwVersion { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MyUplinkConnector.Client.Models.DeviceFirmwareInfoResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MyUplinkConnector.Client.Models.DeviceFirmwareInfoResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MyUplinkConnector.Client.Models.DeviceFirmwareInfoResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currentFwVersion", n => { CurrentFwVersion = n.GetStringValue(); } },
                { "desiredFwVersion", n => { DesiredFwVersion = n.GetStringValue(); } },
                { "deviceId", n => { DeviceId = n.GetStringValue(); } },
                { "firmwareId", n => { FirmwareId = n.GetStringValue(); } },
                { "pendingFwVersion", n => { PendingFwVersion = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("currentFwVersion", CurrentFwVersion);
            writer.WriteStringValue("desiredFwVersion", DesiredFwVersion);
            writer.WriteStringValue("deviceId", DeviceId);
            writer.WriteStringValue("firmwareId", FirmwareId);
            writer.WriteStringValue("pendingFwVersion", PendingFwVersion);
        }
    }
}
