// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MyUplinkConnector.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    /// <summary>Specifies the different connection states of a device.0 - Disconnected1 - Connected</summary>
    public enum DeviceConnectionState
    {
        [EnumMember(Value = "Disconnected")]
        #pragma warning disable CS1591
        Disconnected,
        #pragma warning restore CS1591
        [EnumMember(Value = "Connected")]
        #pragma warning disable CS1591
        Connected,
        #pragma warning restore CS1591
    }
}
