// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MyUplinkConnector.Client.Models
{
    /// <summary>
    /// Group list.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class PagedSystemResult : IParsable
    {
        /// <summary>Connection state.</summary>
        public int? ItemsPerPage { get; set; }
        /// <summary>Firmware.</summary>
        public int? NumItems { get; set; }
        /// <summary>Id.</summary>
        public int? Page { get; set; }
        /// <summary>Groups.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MyUplinkConnector.Client.Models.SystemWithDevices>? Systems { get; set; }
#nullable restore
#else
        public List<global::MyUplinkConnector.Client.Models.SystemWithDevices> Systems { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MyUplinkConnector.Client.Models.PagedSystemResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MyUplinkConnector.Client.Models.PagedSystemResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MyUplinkConnector.Client.Models.PagedSystemResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "itemsPerPage", n => { ItemsPerPage = n.GetIntValue(); } },
                { "numItems", n => { NumItems = n.GetIntValue(); } },
                { "page", n => { Page = n.GetIntValue(); } },
                { "systems", n => { Systems = n.GetCollectionOfObjectValues<global::MyUplinkConnector.Client.Models.SystemWithDevices>(global::MyUplinkConnector.Client.Models.SystemWithDevices.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("itemsPerPage", ItemsPerPage);
            writer.WriteIntValue("numItems", NumItems);
            writer.WriteIntValue("page", Page);
            writer.WriteCollectionOfObjectValues<global::MyUplinkConnector.Client.Models.SystemWithDevices>("systems", Systems);
        }
    }
}
