// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MyUplinkConnector.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public enum Status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "None")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "Active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "DismissedByDevice")]
        #pragma warning disable CS1591
        DismissedByDevice,
        #pragma warning restore CS1591
        [EnumMember(Value = "ResetByUserOnDevice")]
        #pragma warning disable CS1591
        ResetByUserOnDevice,
        #pragma warning restore CS1591
        [EnumMember(Value = "ResetByUserFromCloud")]
        #pragma warning disable CS1591
        ResetByUserFromCloud,
        #pragma warning restore CS1591
        [EnumMember(Value = "Unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
    }
}
