// <auto-generated/>
#pragma warning disable CS0618
using EstfeedConnector.Client.Api.Public.V1.MeteringData;
using EstfeedConnector.Client.Api.Public.V1.MeteringPointEics;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace EstfeedConnector.Client.Api.Public.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \api\public\v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The meteringData property</summary>
        public global::EstfeedConnector.Client.Api.Public.V1.MeteringData.MeteringDataRequestBuilder MeteringData
        {
            get => new global::EstfeedConnector.Client.Api.Public.V1.MeteringData.MeteringDataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The meteringPointEics property</summary>
        public global::EstfeedConnector.Client.Api.Public.V1.MeteringPointEics.MeteringPointEicsRequestBuilder MeteringPointEics
        {
            get => new global::EstfeedConnector.Client.Api.Public.V1.MeteringPointEics.MeteringPointEicsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EstfeedConnector.Client.Api.Public.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EstfeedConnector.Client.Api.Public.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
