// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using MyUplinkConnector.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MyUplinkConnector.Client.V3.Devices.Item.Points
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\devices\{deviceId}\points
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    public partial class PointsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MyUplinkConnector.Client.V3.Devices.Item.Points.PointsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PointsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/devices/{deviceId}/points{?parameters*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MyUplinkConnector.Client.V3.Devices.Item.Points.PointsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PointsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/devices/{deviceId}/points{?parameters*}", rawUrl)
        {
        }
        /// <summary>
        /// Get scaled data point for device.
        /// </summary>
        /// <returns>A List&lt;global::MyUplinkConnector.Client.Models.ParameterData&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::MyUplinkConnector.Client.Models.ParameterData>?> GetAsync(Action<RequestConfiguration<global::MyUplinkConnector.Client.V3.Devices.Item.Points.PointsRequestBuilder.PointsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::MyUplinkConnector.Client.Models.ParameterData>> GetAsync(Action<RequestConfiguration<global::MyUplinkConnector.Client.V3.Devices.Item.Points.PointsRequestBuilder.PointsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::MyUplinkConnector.Client.Models.ParameterData>(requestInfo, global::MyUplinkConnector.Client.Models.ParameterData.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Get scaled data point for device.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MyUplinkConnector.Client.V3.Devices.Item.Points.PointsRequestBuilder.PointsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MyUplinkConnector.Client.V3.Devices.Item.Points.PointsRequestBuilder.PointsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MyUplinkConnector.Client.V3.Devices.Item.Points.PointsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MyUplinkConnector.Client.V3.Devices.Item.Points.PointsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MyUplinkConnector.Client.V3.Devices.Item.Points.PointsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get scaled data point for device.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class PointsRequestBuilderGetQueryParameters 
        {
            /// <summary>Parameter ids separated by comma. Optional parameter:If parameter ids are not defined, then all device&apos;s parameters will be listed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("parameters")]
            public string? Parameters { get; set; }
#nullable restore
#else
            [QueryParameter("parameters")]
            public string Parameters { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
        public partial class PointsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::MyUplinkConnector.Client.V3.Devices.Item.Points.PointsRequestBuilder.PointsRequestBuilderGetQueryParameters>
        {
        }
    }
}
