// <auto-generated/>
#pragma warning disable CS0618
using EstfeedConnector.Client.Api.Public.V1;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace EstfeedConnector.Client.Api.Public
{
    /// <summary>
    /// Builds and executes requests for operations under \api\public
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PublicRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The v1 property</summary>
        public global::EstfeedConnector.Client.Api.Public.V1.V1RequestBuilder V1
        {
            get => new global::EstfeedConnector.Client.Api.Public.V1.V1RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EstfeedConnector.Client.Api.Public.PublicRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PublicRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::EstfeedConnector.Client.Api.Public.PublicRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PublicRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
