// <auto-generated/>
#pragma warning disable CS0618
using DynessConnector.Client.V1.Control.BatchSetChargeConfig;
using DynessConnector.Client.V1.Control.BatchSetChargeDischargeConfig;
using DynessConnector.Client.V1.Control.BatteryCapacitySetting;
using DynessConnector.Client.V1.Control.MaxFeedinSet;
using DynessConnector.Client.V1.Control.SetGirdConnectedPowerLimit;
using DynessConnector.Client.V1.Control.SingleSetChargeConfig;
using DynessConnector.Client.V1.Control.SingleSetChargeDischargeConfig;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DynessConnector.Client.V1.Control
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\control
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ControlRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The batchSetChargeConfig property</summary>
        public global::DynessConnector.Client.V1.Control.BatchSetChargeConfig.BatchSetChargeConfigRequestBuilder BatchSetChargeConfig
        {
            get => new global::DynessConnector.Client.V1.Control.BatchSetChargeConfig.BatchSetChargeConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The batchSetChargeDischargeConfig property</summary>
        public global::DynessConnector.Client.V1.Control.BatchSetChargeDischargeConfig.BatchSetChargeDischargeConfigRequestBuilder BatchSetChargeDischargeConfig
        {
            get => new global::DynessConnector.Client.V1.Control.BatchSetChargeDischargeConfig.BatchSetChargeDischargeConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The batteryCapacitySetting property</summary>
        public global::DynessConnector.Client.V1.Control.BatteryCapacitySetting.BatteryCapacitySettingRequestBuilder BatteryCapacitySetting
        {
            get => new global::DynessConnector.Client.V1.Control.BatteryCapacitySetting.BatteryCapacitySettingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The maxFeedinSet property</summary>
        public global::DynessConnector.Client.V1.Control.MaxFeedinSet.MaxFeedinSetRequestBuilder MaxFeedinSet
        {
            get => new global::DynessConnector.Client.V1.Control.MaxFeedinSet.MaxFeedinSetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The setGirdConnectedPowerLimit property</summary>
        public global::DynessConnector.Client.V1.Control.SetGirdConnectedPowerLimit.SetGirdConnectedPowerLimitRequestBuilder SetGirdConnectedPowerLimit
        {
            get => new global::DynessConnector.Client.V1.Control.SetGirdConnectedPowerLimit.SetGirdConnectedPowerLimitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The singleSetChargeConfig property</summary>
        public global::DynessConnector.Client.V1.Control.SingleSetChargeConfig.SingleSetChargeConfigRequestBuilder SingleSetChargeConfig
        {
            get => new global::DynessConnector.Client.V1.Control.SingleSetChargeConfig.SingleSetChargeConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The singleSetChargeDischargeConfig property</summary>
        public global::DynessConnector.Client.V1.Control.SingleSetChargeDischargeConfig.SingleSetChargeDischargeConfigRequestBuilder SingleSetChargeDischargeConfig
        {
            get => new global::DynessConnector.Client.V1.Control.SingleSetChargeDischargeConfig.SingleSetChargeDischargeConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.V1.Control.ControlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ControlRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/control", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DynessConnector.Client.V1.Control.ControlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ControlRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/control", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
